### ISSUE TITLE
Unexpected error happened while loading datasources settings

### ISSUE THREAD

**Issue by MAGICCC** [grafana/grafana-zabbix#1084]
**Describe the bug**
When I try to load on the datasources settings on latest Grafana + Zabbix version I get following error:
```
An unexpected error happened
TypeError: s is undefined

    in Unknown
    in div
    in t
    in form
    in div
    in div
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in t
    in x
    in ConnectWithCleanUp(Connect(t))
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**Expected behavior**
Should load the settings page fine

**Screenshots**
![image](https://user-images.githubusercontent.com/3279213/97336274-1c524900-187f-11eb-9339-9b2f9cd0bf9c.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v7.2.2 (ad9d408ac2)   | 5.2.0  | 4.0.1                |

**Comment by MAGICCC** [comment]
Note:
I updated to Zabbix 5.2.0 + Grafana v7.2.2 (ad9d408ac2) in one go today
Also adding a new Zabbix datasource works fine and my dashboards are accessible

**Comment by alexanderzobnin** [comment]
Is it still happens?
