### ISSUE TITLE
Plugin unavailable error 503

### ISSUE THREAD

**Issue by mancio00** [grafana/grafana-zabbix#1217]
I'm creating my own grafana 7.5.7 container with zabbix plugin. I'm installing this plugins during container creation
RUN ./bin/grafana-cli plugins install 'alexanderzobnin-zabbix-app'
RUN chmod -R 472 /var/lib/grafana/plugins/alexanderzobnin-zabbix-app

The plugin is successfully installed but it doesn't work.
Looking grafana logs I found these entries
t=2021-05-20T15:33:38+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/4/resources/zabbix-api status=503 remote_addr=192.168.232.107 time_ms=6 size=32 referer="https://XXXXX/grafana/d/N0IM4jXGz/errevi-dashboard-test-logotipo?orgId=1&refresh=30s"

If I try to manually execute the binary into the container it doesn't run
bash-5.1$ /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
bash: /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64: No such file or directory
bash-5.1$ ls -l /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64
-rwxr-xr-x    1 grafana  root      12505088 May 20 15:18 /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/zabbix-plugin_linux_amd64

Grafana 7.5.7
Zabbix 5.2
Grafana-Zabbix Plugin 4.1.5  

Thanks

Matteo

**Comment by arc855** [comment]
Same issue with me also ,
garafana  9.2.1
zabbix 5.2.5
plugin 4.10.2

help me to resolve this issue.
Thanks

**Comment by sirmaxru** [comment]
> help me to resolve this issue. Thanks
just use grafana on ubuntu, if you using docker
tag like `9.3.1-ubuntu`
