### ISSUE TITLE
unstable values

### ISSUE THREAD

**Issue by wardog666** [grafana/grafana-zabbix#1219]
Hello,
I try to display values from an item of type zabbix trapper. And it appears that tiemstamps are not stable (and not corresponds) in regards to zabbix timestamps. Values displayed in the table do not correspond to zabbix. 
Datas change at every refresh (automatic or forced). 
I can get correct values if I play with the time  range cursor.

**Expected behavior**
Display correct values and timestamps according to time range.

**Screenshots**
![20210528_164159](https://user-images.githubusercontent.com/46408467/120002305-fa67a300-bfd4-11eb-939f-0100c00426f3.jpg)
![20210528_164153](https://user-images.githubusercontent.com/46408467/120002311-fb98d000-bfd4-11eb-91f9-aa0b50bc5e79.jpg)

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)
{
    "results": {
        "A": {
            "refId": "A",
            "meta": {
                "executedQueryString": "SELECT CAST(itemid AS CHAR) AS metric, MIN(clock) AS time_sec, AVG(value) AS value FROM history_uint WHERE itemid IN (37816) AND clock > 1622210043 AND clock < 1622213643 GROUP BY (clock-1622210043) DIV 2, metric ORDER BY time_sec ASC",
                "rowCount": 0
            },
            "series": [
                {
                    "name": "37816",
                    "points": [
                        [
                            0,
                            1622210186000
                        ],
                        [
                            1.5,
                            1622210187000
                        ],
                        [
                            3.5,
                            1622210189000
                        ],
                        [
                            5.5,
                            1622210191000
                        ],
                        [
                            7.5,
                            1622210193000
                        ],
                        [
                            6.6667,
                            1622210195000
                        ],
                        [
                            11.5,
                            1622210197000
                        ],
                        [
                            13.5,
                            1622210199000
                        ],
                        [
                            15.5,
                            1622210201000
                        ],
                        [
                            17.5,
                            1622210203000
                        ],
                        [
                            13.6667,
                            1622210205000
                        ],
                        [
                            21.5,
                            1622210207000
                        ],
                        [
                            23.5,
                            1622210209000
                        ],
                        [
                            25.5,
                            1622210211000
                        ],
                        [
                            27.5,
                            1622210213000
                        ],
                        [
                            20.6667,
                            1622210215000
                        ],
                        [
                            31.5,
                            1622210217000
                        ],
                        [
                            33.5,
                            1622210219000
                        ],
                        [
                            35.5,
                            1622210221000
                        ],
                        [
                            37.5,
                            1622210223000
                        ],
                        [
                            27.6667,
                            1622210225000
                        ],
                        [
                            41.5,
                            1622210227000
                        ],
                        [
                            43.5,
                            1622210229000
                        ],
                        [
                            45.5,
                            1622210231000
                        ],
                        [
                            47.5,
                            1622210233000
                        ],
                        [
                            34.6667,
                            1622210235000
                        ],
                        [
                            51.5,
                            1622210237000
                        ],
                        [
                            53.5,
                            1622210239000
                        ],
                        [
                            55.5,
                            1622210241000
                        ],
                        [
                            57.5,
                            1622210243000
                        ],
                        [
                            41.6667,
                            1622210245000
                        ],
                        [
                            61.5,
                            1622210247000
                        ],
                        [
                            63.5,
                            1622210249000
                        ],
                        [
                            65.5,
                            1622210251000
                        ],
                        [
                            67.5,
                            1622210253000
                        ],
                        [
                            48.6667,
                            1622210255000
                        ],
                        [
                            71.5,
                            1622210257000
                        ],
                        [
                            73.5,
                            1622210259000
                        ],
                        [
                            75.5,
                            1622210261000
                        ],
                        [
                            77.5,
                            1622210263000
                        ],
                        [
                            55.6667,
                            1622210265000
                        ],
                        [
                            81.5,
                            1622210267000
                        ],
                        [
                            83.5,
                            1622210269000
                        ],
                        [
                            85.5,
                            1622210271000
                        ],
                        [
                            87.5,
                            1622210273000
                        ],
                        [
                            62.6667,
                            1622210275000
                        ],
                        [
                            91.5,
                            1622210277000
                        ],
                        [
                            93.5,
                            1622210279000
                        ],
                        [
                            95.5,
                            1622210281000
                        ],
                        [
                            97.5,
                            1622210283000
                        ],
                        [
                            69.6667,
                            1622210285000
                        ],
                        [
                            11,
                            1622210296000
                        ],
                        [
                            12,
                            1622210306000
                        ],
                        [
                            13,
                            1622210316000
                        ],
                        [
                            14,
                            1622210326000
                        ],
                        [
                            15,
                            1622210336000
                        ],
                        [
                            16,
                            1622210346000
                        ],
                        [
                            17,
                            1622210356000
                        ],
                        [
                            18,
                            1622210366000
                        ],
                        [
                            19,
                            1622210376000
                        ],
                        [
                            20,
                            1622210386000
                        ],
                        [
                            21,
                            1622210396000
                        ],
                        [
                            22,
                            1622210406000
                        ],
                        [
                            23,
                            1622210416000
                        ],
                        [
                            24,
                            1622210426000
                        ],
                        [
                            25,
                            1622210436000
                        ],
                        [
                            26,
                            1622210446000
                        ],
                        [
                            27,
                            1622210456000
                        ],
                        [
                            28,
                            1622210466000
                        ],
                        [
                            29,
                            1622210476000
                        ],
                        [
                            30,
                            1622210486000
                        ],
                        [
                            31,
                            1622210496000
                        ],
                        [
                            32,
                            1622210506000
                        ],
                        [
                            33,
                            1622210516000
                        ],
                        [
                            34,
                            1622210526000
                        ],
                        [
                            35,
                            1622210536000
                        ],
                        [
                            36,
                            1622210546000
                        ],
                        [
                            37,
                            1622210556000
                        ],
                        [
                            38,
                            1622210566000
                        ],
                        [
                            39,
                            1622210576000
                        ],
                        [
                            40,
                            1622210586000
                        ],
                        [
                            41,
                            1622210596000
                        ],
                        [
                            42,
                            1622210606000
                        ],
                        [
                            43,
                            1622210616000
                        ],
                        [
                            44,
                            1622210626000
                        ],
                        [
                            45,
                            1622210636000
                        ],
                        [
                            46,
                            1622210646000
                        ],
                        [
                            47,
                            1622210656000
                        ],
                        [
                            48,
                            1622210666000
                        ],
                        [
                            49,
                            1622210676000
                        ],
                        [
                            50,
                            1622210686000
                        ],
                        [
                            51,
                            1622210696000
                        ],
                        [
                            52,
                            1622210706000
                        ],
                        [
                            53,
                            1622210716000
                        ],
                        [
                            54,
                            1622210726000
                        ],
                        [
                            55,
                            1622210736000
                        ],
                        [
                            56,
                            1622210746000
                        ],
                        [
                            57,
                            1622210756000
                        ],
                        [
                            58,
                            1622210766000
                        ],
                        [
                            59,
                            1622210776000
                        ],
                        [
                            60,
                            1622210786000
                        ],
                        [
                            61,
                            1622210796000
                        ],
                        [
                            62,
                            1622210806000
                        ],
                        [
                            63,
                            1622210816000
                        ],
                        [
                            64,
                            1622210826000
                        ],
                        [
                            65,
                            1622210836000
                        ],
                        [
                            66,
                            1622210846000
                        ],
                        [
                            67,
                            1622210856000
                        ],
                        [
                            68,
                            1622210866000
                        ],
                        [
                            69,
                            1622210876000
                        ],
                        [
                            70,
                            1622210886000
                        ],
                        [
                            71,
                            1622210896000
                        ],
                        [
                            72,
                            1622210906000
                        ],
                        [
                            73,
                            1622210916000
                        ],
                        [
                            74,
                            1622210926000
                        ],
                        [
                            75,
                            1622210936000
                        ],
                        [
                            76,
                            1622210946000
                        ],
                        [
                            77,
                            1622210956000
                        ],
                        [
                            78,
                            1622210966000
                        ],
                        [
                            79,
                            1622210976000
                        ],
                        [
                            80,
                            1622210986000
                        ],
                        [
                            81,
                            1622210996000
                        ],
                        [
                            82,
                            1622211006000
                        ],
                        [
                            83,
                            1622211016000
                        ],
                        [
                            84,
                            1622211026000
                        ],
                        [
                            85,
                            1622211036000
                        ],
                        [
                            86,
                            1622211046000
                        ],
                        [
                            87,
                            1622211056000
                        ],
                        [
                            88,
                            1622211066000
                        ],
                        [
                            89,
                            1622211076000
                        ],
                        [
                            90,
                            1622211086000
                        ],
                        [
                            91,
                            1622211096000
                        ],
                        [
                            92,
                            1622211106000
                        ],
                        [
                            93,
                            1622211116000
                        ],
                        [
                            94,
                            1622211126000
                        ],
                        [
                            95,
                            1622211136000
                        ],
                        [
                            96,
                            1622211146000
                        ],
                        [
                            97,
                            1622211156000
                        ],
                        [
                            98,
                            1622211166000
                        ],
                        [
                            99,
                            1622211176000
                        ],
                        [
                            100,
                            1622211186000
                        ]
                    ]
                }
            ],
            "tables": null,
            "dataframes": null
        }
    }
}

**Software versions**
| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.5.7   | 5.4.0  | 4.1.5                 |

**Comment by alexanderzobnin** [comment]
Hi! Try to disable data alignment in the query options.
