### ISSUE TITLE
Polystat TypeError: this.datapoints is undefined some data missing 

### ISSUE THREAD

**Issue by MGlants** [grafana/grafana-zabbix#1220]
**Describe the bug**
Polystat stoped working after update 4.1.3

**Expected behavior**
Polystat was so useful to display large amount of nodes

**Screenshots**
![image](https://user-images.githubusercontent.com/35956828/120463330-792d5900-c3a4-11eb-9f6f-e93544d6109b.png)
![image](https://user-images.githubusercontent.com/35956828/120463927-0f617f00-c3a5-11eb-9564-452e8cb5a51c.png)

**Network data**
`  TypeError: this.datapoints is undefined

    in t
    in Cn
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in oi
    in div
    in t
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 7.3.6   | 5.2.6  | 4.1.5                |

**Comment by alexanderzobnin** [comment]
Looks like plugin does not support data frame format. It's better to open issue in the plugin repo. CC @briangann.

**Comment by briangann** [comment]
just fyi: a new release of polystat v1.2.4 is out with dataframe support
