### ISSUE TITLE
Plugin not found, no installed plugin with that id

### ISSUE THREAD

**Issue by ykishanreddy** [grafana/grafana-zabbix#1226]

**Comment by ykishanreddy** [comment]
when I restart grafana zabix datasource is getting issue like below
![Screenshot 2021-06-11 183302](https://user-images.githubusercontent.com/46573501/121690793-edbe7100-cae3-11eb-8a49-f4708aba74f8.png)
![Screenshot 2021-06-11 183421](https://user-images.githubusercontent.com/46573501/121690801-eeef9e00-cae3-11eb-8c80-accb3cbcc51f.png)

  so I removed zabbix plugin reinstalled but still not resolved

**Comment by ykishanreddy** [comment]
when I restart grafana server the zabbix datasource getting issue like below, So then I removed zabbix plugin and reinstalled but still not resolved
![Screenshot 2021-06-11 184202](https://user-images.githubusercontent.com/46573501/121691865-1a26bd00-cae5-11eb-9b57-df96688c88d9.png)
![Screenshot 2021-06-11 183421](https://user-images.githubusercontent.com/46573501/121691860-18f59000-cae5-11eb-8391-374a9b7a0640.png)

**Comment by xiaotianlu** [comment]
show grafana and zabbix version

**Comment by iliesh** [comment]
I have the same issue, which started after I upgraded the grafana to the 8'th version.
Grafana: Version 8.0.1 (commit: 8849243d27, branch: HEAD)
Zabbix: (Zabbix) 4.4.10

**Comment by reissmann** [comment]
Same issue with the OpenNMS Datasource (opennms-helm), after upgrading from grafana 7 to 8.0.5.
Even if I remove all OpenNMS related plugins and datasources using grafana-cli, the datasource is still shown in the UI, and I am unable to remove it.
