### ISSUE TITLE
Single host items contain the hostname in the legend

### ISSUE THREAD

**Issue by osas1111** [grafana/grafana-zabbix#1335]
**Describe the bug**
Since 4.2.0 version of Grafana plugin I facing a problem with legend presentation. For single host items hostname is present the same as for multi-host graph/time_series. These changes was not present in change logs so I want to make sure before changing my dashboards for new version

**Expected behavior**
No hostname in legend for single host graph/time_series

**Screenshots**
expected:
![image](https://user-images.githubusercontent.com/6796180/138424029-5f938cf6-674f-4395-ac71-b047ebb06c3f.png)

current:
![image](https://user-images.githubusercontent.com/6796180/138424388-73d11660-3512-4465-a17a-8518838738ce.png)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.1.4   | 5.4.4  | 4.2.4                 |

**Comment by Phobos-7** [comment]
I've managed to remediate this using setAlias and replaceAlias... But still, it would be better not to show hostname by default.

**Comment by rike50** [comment]
Same problem here
Grafana 8.4.2, Zabbix 5.2.7, Grafana-Zabbix 4.2.5

**Comment by stvolinko** [comment]
Got same on my testing instalation:
Grafana:  8.2.6
Zabbix-plugin: 4.2.5
Zabbix: 5.0.19

**Comment by alexanderzobnin** [comment]
There's a workaround - you can use `setAlias($__zbx_item_name)` to force plugin use only item name.

**Comment by alexanderzobnin** [comment]
@vryzhevsky Yes, I agree, that's why I called it a workaround. I'm looking into this issue, seems, it's not that straightforward since plugin now uses data frame format for response, but I hope I can find out a solution.

**Comment by vryzhevsky** [comment]
Hi, new version 4.1.1 did not fix the issue

**Comment by isaqueprofeta** [comment]
You should use replaceAlias function to remove the hostname part. look at the steps on this video: https://youtu.be/-dT8Yu0Upk4?list=PLTAdaA8clXXK9A9rPjBKqxho4AGSTb6un&t=352

**Comment by onanok** [comment]
When using "Direct DB Connection" on  version 4.4.3 , still not fixed
