### ISSUE TITLE
Graph Scaling of different data sources is not correct

### ISSUE THREAD

**Issue by crosenbe** [grafana/grafana-zabbix#1397]
Different data sources does not scale to the selected time frame. Due to whatever reason this issues are there or not there, sometimes it works as expected.

Fetch three data sources, two of them stick to axis Y1, the third to axis Y2. The amount of data points differs between all data sources. The data points should scale in the graph from left to right, filling the complete area. But the third value of Y2 end a bit earlier, this is a mismatch to Y1 regarding the time frame.

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.3.3    | 5.4     | 4.2.4                        |

**Comment by alexanderzobnin** [comment]
Hi! Could you attach a screenshot? It seems, I also noticed this, but I think it's something new in Grafana rather than in plugin. Anyway, that might be annoing, so I'll try to investigate.

**Comment by zoltanbedi** [comment]
Can you please provide steps to reproduce this?

**Comment by gabor** [comment]
hi, as we got no new info in a long time, we're closing the issue for now. we can reopen it when we receive new information. thank you!
