### ISSUE TITLE
direct db connection (postgresql) - problem

### ISSUE THREAD

**Issue by layer3lv** [grafana/grafana-zabbix#1401]
Hi, 

when I try to use "Direct DB Connection" I got an error - "Could not connect to given URL"

grafana 8.4
latest zabbix plugin 
PostgreSQL 13

p.s

from grafana.log

logger=plugin.alexanderzobnin-zabbix-datasource t=2022-02-24T12:50:55.54+0200 lvl=dbug msg="Zabbix request" method=hostgroup.get
logger=plugin.alexanderzobnin-zabbix-datasource t=2022-02-24T12:50:55.56+0200 lvl=dbug msg="Writing result to cache" method=hostgroup.get
logger=datasources t=2022-02-24T12:50:55.58+0200 lvl=dbug msg="Querying for data source via SQL store" id=21 orgId=1
logger=query_data t=2022-02-24T12:50:55.58+0200 lvl=dbug msg="Processing metrics query" query="unsupported value type"
logger=context t=2022-02-24T12:50:55.59+0200 lvl=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=127.0.0.1 time_ms=9 size=324

**Comment by alexanderzobnin** [comment]
Could you describe your config a bit more?

**Comment by jpcapone** [comment]
Same here.  Any updates?

**Comment by BitzGaelleG** [comment]
Hello,
I have the same problem with grafana v10.4.1, using a Postgresql 16 database and Zabbix version 7.0.0. The connection to the db alone works fine, and the one to Zabbix as well. But when adding the "Enable Direct DB Connection", i get the "Could not connect to given URL" error. Any idea on how to fix it or a work around ?
Thanks

**Comment by zoltanbedi** [comment]
I'm going to close this as it seems like the error is from a misconfigured data source.
