### ISSUE TITLE
Could not connect to given url

### ISSUE THREAD

**Issue by tko-mz** [grafana/grafana-zabbix#1448]
I use Zabbix with TLS, and am getting the below errors when trying to setup the data source. 
I can receive data from the zabbix api using the same URL using curl. Grafana is running in docker. 

If I check TLS Client Auth (with the cert added) or Skip TLS Verify I receive the below error.
**Could not connect to given url**

If I uncheck TLS Client Auth or Skip TLS Verify I receive the below error.
**x509: certificate signed by unknown authority**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v8.4.1   | 6.0.3  | 4.2.8                |

Any ideas of what would be the cause or what I else I could check?

**Comment by NEODjazz** [comment]
I've got same error without TLS 

- Zabbix 4.0.5
- Grafana 8.5.2
- Zabbix Plugin 4.2.8
