### ISSUE TITLE
Hi Alexander, how to clasificate hosts by country with tags or hostgroup

### ISSUE THREAD

**Issue by odelacruz93** [grafana/grafana-zabbix#1454]
Hi Alexander, how to clasificate hosts by country with tags or hostgroup in grafana. For example in grafana I have 2 organizations by country, but in zabbix I have all host with tags PAIS:XXX and have a lot of hostgroups by platform (service1,service2,service3)

how can I separate the hosts by country in grafana with zabbix datasource?

**Comment by sdvidal** [comment]
hi, you can create different accounts in zabbix for different countries, than use different datasources for each grafana´s organization.
