### ISSUE TITLE
Data source not available

### ISSUE THREAD

**Issue by dantte-lp** [grafana/grafana-zabbix#1459]
Good afternoon.
The data source cannot load, although it is added to the exceptions

**Screenshots**
![2022-06-10_120908](https://user-images.githubusercontent.com/46395539/173010453-9450abe0-ffbd-4fa3-a1ce-97efcfbd8a17.png)
![2022-06-10_121210](https://user-images.githubusercontent.com/46395539/173010951-7443e7e9-a43f-4b4b-83d0-a35e017d6c4f.png)
[alexanderzobnin-zabbix-datasource.log](https://github.com/alexanderzobnin/grafana-zabbix/files/8876641/alexanderzobnin-zabbix-datasource.log)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 8.5.5  | 6.0.0  | 4.2.8                 |

Oracle Linux Server release 8.6
5.4.17-2136.304.4.5.el8uek.x86_64 #2 SMP Wed Mar 9 15:08:23 PST 2022 x86_64 x86_64

**Comment by dantte-lp** [comment]
@giovanny07 
Hello.
The plugin is activated, zabbix does not play a role here at all, since the datasource does not appear in the list in grafana itself.

**Comment by dantte-lp** [comment]
I found this in error log nginx
`2022/06/16 07:48:22 [error] 37772#37772: *1 open() "/usr/share/grafana/public/plugins/alexanderzobnin-zabbix-app/module.js" failed (2: No such file or directory), client: 172.21.20.119, server: grf-bor.xxxx.xxxx, request: "GET /public/plugins/alexanderzobnin-zabbix-app/module.js?_cache=4.2.8 HTTP/2.0", host: "grf-bor.xxxx.xxxx", referrer: "https://grf-bor.xxxx.xxxx/plugins/alexanderzobnin-zabbix-app"`

**Comment by dantte-lp** [comment]
Figured out, the problem was in nginx, he incorrectly redirected to the module.js, which is why the config page was not available

![image](https://user-images.githubusercontent.com/46395539/173997235-978f16df-57f4-4e3b-8a78-1d87cbc8d749.png)

**Comment by jorlandobr** [comment]
@dantte-lp,

could you elaborate how did you solved that problem?

My system upgraded to grafana 9.0.1 and now I lost zabbix graphics.

**Comment by baur** [comment]
Grafana 10
Zabbix plugin installed and enabled but Data source ZABBIX is not available

![image](https://github.com/grafana/grafana-zabbix/assets/2898361/488e0541-31ae-4477-8fa2-112b44db602c)

```
logger=context userId=1 orgId=1 uname=admin t=2023-10-18T10:26:09.6947604+06:00 level=error msg="Request Completed" method=GET path=/api/gnet/plugins/alexanderzobnin-zabbix-app status=502 remote_addr=xx.xx.xx.xx time_ms=10 duration=10.0012ms size=0 referer=http://karvideoserv03:3000/plugins/alexanderzobnin-zabbix-app handler=/api/gnet/*
```

**Comment by zoltanbedi** [comment]
@baur can you please open a separate issue with what you think is the issue?
