### ISSUE TITLE
Problems panel: "Resolved" events show in "Problem" state. Differs from Zabbix problems history. Also Age of problem does not match Zabbix.

### ISSUE THREAD

**Issue by stevene1900** [grafana/grafana-zabbix#1464]
When viewing problems history via Grafana, triggers that have gone into Resolved state are showing as Problem state. This could be because the most recent open Problem is same trigger to thoses that have gone into Resolved state, but in Zabbix the older Problems are in "Resovled" status. Also, the Age data for each problem in Grafana does not match Zabbix problem Duration for each event. 

We'd like for the Grafana Problems panel to show data as it appears in Zabbix GUI Problems section.

This is same host and history of problems from Grafana and Zabbix. You will see most recent problem is in Problem state in Zabbix GUI and all rest are Resolved. BUT in Grafana screenshot, you will see ALL problems in Problem state. Also, the age/duration do not alight between the systems.

GRAFANA:
![Grafana Zabbix Problems](https://user-images.githubusercontent.com/107708291/174346371-92095ed6-bfe7-49de-b73c-51d40c369db4.png)

ZABBIX:
![Zabbix GUI Problems](https://user-images.githubusercontent.com/107708291/174346393-3c3344ae-c4ec-400b-bb79-5c76c2c8fcf2.png)

Zabbix 4.2.8
Grafana 8.2.3
Grafana-Zabbix Plugin 4.2.8

**Comment by giovanny07** [comment]
The first recomendation is not use zabbix unsupported version. Upgrade at less 5.0 or 6.0  LTS.
Nest, attach the query json of the panel to help you :D

**Comment by AlOliveira88** [comment]
Hello.

Is it possible to import this dashboard into my grafana?
It's very good

Thanks
