### ISSUE TITLE
Failed to call resource : ResourceExhausted desc = grpc: received message larger than max / Plugin Issue

### ISSUE THREAD

**Issue by IlefMEDINI** [grafana/grafana-zabbix#1492]
Hello,

We have an Internal Server Error : Failed to call resource, when we browse a large data for 30 days as time range, we have to mention that if we apply a smaller time range, data is displayed (when the time range is between 1 and 27 days), so it seems that it's the plugin !

the logs show :
"level=error msg="Failed to call resource" error="failed to receive call resource response: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (18102820 vs. 16777216)" traceID=00000000000000000000000000000000"

So we think that it's caused by the amount of resources allocated, it is not enough : The received message/response is larger than the max, and to solve this problem we need to know if it's possible to reconfigure and to increase this max ! So could you please tell us how to do it ?

**Environment** : Grafana V9.0.2 / Zabbix 6.0. / Grafana-Zabbix Plugin: 4.2.9

Best regards,

**Comment by mjtrangoni** [comment]
Hi,
If you look at the Datasource Configuration, you will find "Zabbix API details". See [here](https://alexanderzobnin.github.io/grafana-zabbix/configuration/). You can play around reducing the values there in Trends, After, and Range. Maybe you are overusing history data, and you need to look to use more trends.

**Comment by IlefMEDINI** [comment]
Hello,

Thank you for your answer, but actually this is not what I would like, I would like to be able to recover the data without reducing the data and for that it is necessary to configure the parameters (to modify and increase the max).
Any idea for this ? 

Thank you
