### ISSUE TITLE
Grafana plugin still using parameter "selectGroups" which has been deprecated since Zabbix 6.2.0

### ISSUE THREAD

**Issue by Cacha21** [grafana/grafana-zabbix#1505]
**Describe the bug**
Apparently the Grafana plugin is using the selectGroups parameter which has been deprecated since Zabbix 6.2.0. This is filling the /var/log/httpd/errror_log log file.

**Expected behavior**
Grafana should be using the new option selectHostGroups instead according to:
https://www.zabbix.com/documentation/current/en/manual/api/changes_6.0_-_6.2

This would stop the error logs.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 9.0.5   | 6.2.2  | 4.2.10                 |

**Comment by FlanniganColum** [comment]
Anyone find a solution to this. I have just performed an upgrade to 6.2.X and grafana no longer works
