### ISSUE TITLE
I can't add zabbix datasource to grafana

### ISSUE THREAD

**Issue by laurixia** [grafana/grafana-zabbix#1582]
Not added to the zabbix datasource

**Expected behavior**
I use basic authentication with admin user and password but it does not connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/26741776/223481993-7ff114b5-c9aa-46ea-9d78-afa7ac34e62c.png)
![image](https://user-images.githubusercontent.com/26741776/223482452-44bf67a8-de7f-41b7-bb85-f0f6a3523cc8.png)
![image](https://user-images.githubusercontent.com/26741776/223484843-d4d9e970-9e3d-4f03-b8fa-a0abdee75e6e.png)
![image](https://user-images.githubusercontent.com/26741776/223486625-d89c1624-bb47-430f-885e-04bcbb773953.png)

**Software versions**

Grafana 9.1.0
Zabbix 6.2
Grafana-Zabbix Plugin 4.2.10

**Comment by brunocarvalhoti** [comment]
Do you use any proxy like nginx or apache? If so, did you configure any ports on the proxy? For me it works as follows: http://IP:PORT/api_jsonrpc.php, without using /zabbix in the address, that must be the problem.

**Comment by laurixia** [comment]
Done.
