### ISSUE TITLE
plugin version 4.3.0 query ignoring selected application

### ISSUE THREAD

**Issue by net16789** [grafana/grafana-zabbix#1597]
After updating Grafana-Zabbix plugin to 4.3.0, item queries are no longer limited to the selected application.

In a query, selecting a Group, Host, Application then clicking the item field - all items associated with the host are presented.
The expected behavior as experienced with Grafana-Zabbix plugin 4.2.10 is that only items contained in the selected application would be presented, not all host items.
With Grafana-Zabbix plugin 4.3.0 this results in item query regex matching against all host items.
For example in addition to items in the CPU application, this query now unexpectedly returns items in the Memory application.
![query](https://user-images.githubusercontent.com/128723300/227261739-8f2b5f08-6e0b-4ec3-b83d-52b223a982f6.png)

Environment:
Grafana-Zabbix plugin: 4.3.0, Direct DB Connection enabled
Grafana: v9.4.3
Zabbix: 5.0.3, MySQL DB

**Comment by alexanderzobnin** [comment]
Ok, I'll try to test it out against Zabbix 5.0

**Comment by Teofaness** [comment]
> After updating Grafana-Zabbix plugin to 4.3.0, item queries are no longer limited to the selected application.
> 
> In a query, selecting a Group, Host, Application then clicking the item field - all items associated with the host are presented. The expected behavior as experienced with Grafana-Zabbix plugin 4.2.10 is that only items contained in the selected application would be presented, not all host items. With Grafana-Zabbix plugin 4.3.0 this results in item query regex matching against all host items. For example in addition to items in the CPU application, this query now unexpectedly returns items in the Memory application. ![query](https://user-images.githubusercontent.com/128723300/227261739-8f2b5f08-6e0b-4ec3-b83d-52b223a982f6.png)
> 
> Environment: Grafana-Zabbix plugin: 4.3.0, Direct DB Connection enabled Grafana: v9.4.3 Zabbix: 5.0.3, MySQL DB

I have a same problem!

**Comment by alexanderzobnin** [comment]
Could you please confirm it with the latest plugin version? I cannot replicate the issue, in my case app filter works correctly. I tried Zabbix 5.0 and 5.2.

**Comment by alexanderzobnin** [comment]
The only thing I've found that seems to be working not as expected is when app filter is specified, but app is not found. In this case all items will be returned and app filter works as empty. So try to double check you have correct app name.

**Comment by rike50** [comment]
> The only thing I've found that seems to be working not as expected is when app filter is specified, but app is not found. In this case all items will be returned and app filter works as empty. So try to double check you have correct app name.

Correct, i test the same thing with plugin v 4.3.1 and Zabbix 5.2.7, there is no issue, except if app doesn't exist.

**Comment by Teofaness** [comment]
> A única coisa que descobri que parece não estar funcionando conforme o esperado é quando o filtro do aplicativo é especificado, mas o aplicativo não é encontrado. Nesse caso, todos os itens serão retornados e o filtro do aplicativo funciona como vazio. Portanto, tente verificar se o nome do aplicativo está correto.


The error only occurs with the zabbix 5 version as shown in the photo below
on version 5.0
![image](https://github.com/grafana/grafana-zabbix/assets/87394630/2b100bbb-a0a3-41fc-9d42-5816306ae923)

on version 6.0
![image](https://github.com/grafana/grafana-zabbix/assets/87394630/f5a20b3f-5dc6-46ee-a67e-cbf48971cb4c)

**Comment by alexanderzobnin** [comment]
Ok, so I'm closing this as solved.

**Comment by e-nighthaven** [comment]
so, it won't be fixed for zabbix 5.0?

**Comment by yoke88** [comment]
zabbix 4.0.18 with grafana-zabbix 4.4.6 filtering items by applications not work
![image](https://github.com/grafana/grafana-zabbix/assets/3146226/32fb8188-cbf0-4483-9bf4-8563ad5646ff)
