### ISSUE TITLE
Problems: Able to select AND/OR tag evaluation rule

### ISSUE THREAD

**Issue by AlexIta95** [grafana/grafana-zabbix#1600]
Good morning,

yesterday after the Grafana upgrade to version 9.4.7 we are experiencing an anomaly in the selection of tags for the "Zabbix problem" widget.
Before yesterday when I put 2 tags, only the problems that respected both tags appeared, so the rule was (Tag1) AND (Tag2)
With the new version, he shows me all problems that contain either Tag1 or Tag2, no longer just problems that contain both.

Zabbix version 6.0
Grafana version 9.4.7

<img width="647" alt="Cattura" src="https://user-images.githubusercontent.com/37298059/228769760-80bac0e5-9f92-41ea-be70-5c2b72e53511.PNG">

**Comment by alexanderzobnin** [comment]
Hi! Yes, this behavior was changed. But I think since there're different use cases, it makes sense to add And/Or switch for tag evaluation.

**Comment by alexanderzobnin** [comment]
I labeled it as a bug because it breaks existing behavior. What I think is needs to be done is:
1. Revert default behavior to AND operator
2. Add operator selector AND/OR
