### ISSUE TITLE
IT Services: multiple SLA issue

### ISSUE THREAD

**Issue by cpinheiro** [grafana/grafana-zabbix#1603]
I applied your new plugin to solve a grafana display problem regarding the dashboard function using a qyery tupe of type services, where in the previous version the service had the SLA nomenclature.
However, I still cannot bring/display the services SLI function, I would like to see the result in the form of a percentage per service item/line and not the status code.
Can you guide me?
see print.
![SERVICE_PROPERTY_SLI](https://user-images.githubusercontent.com/129403844/228861569-5670d2ec-9e30-4234-94cc-8213bf907d9e.PNG)
![SERVICE_PROPERTY_STATUS](https://user-images.githubusercontent.com/129403844/228861578-57835ab5-05b1-42e2-bf2a-df6ddc559330.PNG)

**Comment by alexanderzobnin** [comment]
Looks like a bug. I'll try to investigate.

**Comment by kamulchik** [comment]
Hello. 4.3.1. Have a same issue. SLI, Uptime, Downtime
