### ISSUE TITLE
Method not found. Incorrect API "sla".

### ISSUE THREAD

**Issue by EdisonRobertoJr** [grafana/grafana-zabbix#1630]
**Describe the bug**
Após atualizar o Grafana para a versao v9.3.13 (f9f6d58de3) e o plugin para a versão  9.3.1 a função services dos dashboards começarama gerar esse erro para todas as propriedades: 
( error:"Internal Server Error"
message:"Method not found. Incorrect API \"sla\".")

**Screenshots**
![image](https://github.com/alexanderzobnin/grafana-zabbix/assets/49328470/20475475-8bbf-4834-bcdb-ae9e89bc7cdc)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 9.3.13  | 5.0.11 and 5.4.13  | 9.3.1               |

**Comment by luuuuuh** [comment]
same problem

**Comment by luuuuuh** [comment]
O problema persiste mesmo atualizando o Grafana para versão 10.x e o Zabbix pligin para versão 4.4.3

![image](https://github.com/grafana/grafana-zabbix/assets/23240536/3f271b91-5749-4e1c-af72-8b1a897ec936)

**Comment by zoltanbedi** [comment]
Hey the sla endpoint support is only available in zabbix version 6 and above.
