### ISSUE TITLE
Unable to Install Plugin

### ISSUE THREAD

**Issue by carter-coder** [grafana/grafana-zabbix#1631]
I am failing to install the grafana-zabbix plugin. Can you please assist?

I am on a server that is running Centos7. I used the command `sudo grafana-cli plugins install alexanderzobnin-zabbix-app` and this is the output I got `✔ Downloaded and extracted alexanderzobnin-zabbix-app v4.3.1 zip successfully to /var/lib/grafana/plugins/alexanderzobnin-zabbix-app. Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.` 
When I login on the Grafana GUI and navigate to Plugins, I do not have the option to enable it. I only have the option to install it and when I do press install it fails to install. 

<img width="759" alt="image" src="https://github.com/alexanderzobnin/grafana-zabbix/assets/82453066/7fa02171-f9ff-4347-ac37-e40e3d48e91d">

**Comment by achraf-sani** [comment]
Hey there, would you check what are the permissions for this folder `/var/lib/grafana/plugins` ? 
I had the same problem but i was installing the plugin through Ansible.

**Comment by willzhang** [comment]
I have same error

https://grafana.com/docs/plugins/alexanderzobnin-zabbix-app/latest/installation/


if you install with this command
```
root@zabbix-server:~# grafana-cli plugins install alexanderzobnin-zabbix-app
```
you will find the plugins directory is root user
```
root@zabbix-server:~# ll /var/lib/grafana/ | grep plugins
drwxr-x---  2 root    root          6 Jul  1 20:29 plugins/
```
i must uninstall it and remove plugins

```
root@zabbix-server:~# grafana-cli plugins  uninstall alexanderzobnin-zabbix-app
rm -rf /var/lib/grafana/plugins
```

then install in dashboard
![image](https://github.com/grafana/grafana-zabbix/assets/33590311/2a46c1f4-6fd8-40bd-b42a-bae31d5588f9)

**Comment by zoltanbedi** [comment]
I'm going to close this issue as it seems like it was resolved. Thanks for the detailed explanation @willzhang
