### ISSUE TITLE
Zabbix 6.4

### ISSUE THREAD

**Issue by iny** [grafana/grafana-zabbix#1633]
On Zabbix 6.4 version, I am encountering the following error. Is there any way to circumvent this problem? Or will there be an update about it soon?

`FastCGI sent in stderr: "PHP message: PHP Deprecated:  Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1474PHP message: PHP Deprecated:  Parameter "/real_hosts" is deprecated.`

Zabbix 6.4.1
Grafana v9.4.7
Grafana-Zabbix Plugin 4.3.1

**Comment by rmaiquez** [comment]
I have encountered the same error

Zabbix 6.4.3
Grafana v9.4.12
Grafana-Zabbix Plugin 4.3.1

**Comment by Gkad** [comment]
When this eill be fixed?

**Comment by Omega-Networks** [comment]
Likely due to the update of Zabbix 6.4 API. 

The plugin is now required to send username as "username" rather than "user". 

We ran into this issue with our SWIFT app after upgrading to 6.4.

**Comment by 473255696** [comment]
I have encountered the same error 'FastCGI sent in stderr: "PHP message: PHP Deprecated:  Parameter "/auth" is deprecated. in CApiInputValidator.php on line 1475" while reading response header from upstream, client:

**Comment by rroethof** [comment]
Same here:
2023/08/23 14:10:53 [error] 805#805: *43803 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "monitor.sdc1.anylinq.com"

**Comment by kaellego** [comment]
I have the same error message

PHP message: PHP Deprecated: Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475PHP message: PHP Deprecated: Parameter "/real_hosts" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: 10.10.3.176, server: _, request: "POST /api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "localhost"

and

PHP message: PHP Deprecated: Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: 127.0.0.1, server: _, request: "POST /api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/zabbix.sock:", host: "localhost"

Zabbix 6.4.10
Grafana v10.2.2
Plug-in Grafana-Zabbix 4.4.4

**Comment by evertonpaiva** [comment]
Grafana plugin is not working here too.

Container `zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest` when I clicked "Save and Test" at Grafana Datasource config page:

`2024/01/10 11:15:33 [error] 20#20: *41137 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475PHP message: PHP Deprecated:  Parameter "/real_hosts" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: 172.18.0.1, server: zabbix, request: "POST //api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "xxxxx.xxxxx.xxx.xx.xxx"`

- Zabbix: **6.4.10**
- Grafana: **v10.2.3**
- Plugin Grafana-Zabbix: **4.4.4**

**Comment by evertonpaiva** [comment]
> Grafana plugin is not working here too.
> 
> Container `zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest` when I clicked "Save and Test" at Grafana Datasource config page:
> 
> `2024/01/10 11:15:33 [error] 20#20: *41137 FastCGI sent in stderr: "PHP message: PHP Deprecated: Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475PHP message: PHP Deprecated: Parameter "/real_hosts" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: 172.18.0.1, server: zabbix, request: "POST //api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "xxxxx.xxxxx.xxx.xx.xxx"`
> 
> * Zabbix: **6.4.10**
> * Grafana: **v10.2.3**
> * Plugin Grafana-Zabbix: **4.4.4**

PLugin Version **4.4.5** solved my problem.  🎉

Thanks!

**Comment by zoltanbedi** [comment]
Thanks for verifying @evertonpaiva. I'm going to close this issue then.

**Comment by StipGod** [comment]
Hey so I am currently using the Amazon manaded Grafana, and the Zabbix plugin is not working for me either. I upgraded the plugin version as mentioned here, but it still didnt work. While setting up the datasource, the first connection of the plugin is established correctly, but for the following queries I get: **Post "http://web.zabbix:8080/zabbix/api_jsonrpc.php": dial tcp 10.156.41.36:8080: i/o timeout**


The error log in zabbix is as follows:
 
**[error] 41#41: *504341 FastCGI sent in stderr: "PHP message: PHP Deprecated: Parameter "/auth" is deprecated. in /usr/share/zabbix/include/classes/validators/CApiInputValidator.php on line 1475" while reading response header from upstream, client: xxx, server: zabbix, request: "POST /zabbix/api_jsonrpc.php HTTP/1.1", upstream: "fastcgi://unix:/tmp/php-fpm.sock:", host: "xxx"**

I had a previous installment of Grafana v10.4.1 where this log also appeared, but didnt seem to be an issue and the plugin would work as expected. 

- Zabbix: 6.4.11
- Grafana: 9.4.7
- Plugin Grafana-Zabbix: 4.4.6
