### ISSUE TITLE
Dashboard Template zabbix_system_status.json e.options is undefined

### ISSUE THREAD

**Issue by ITfromHell** [grafana/grafana-zabbix#1639]
**Describe the bug**
I imported the default dashboard from https://github.com/alexanderzobnin/grafana-zabbix/blob/master/dashboards/zabbix_system_status.json
The UI tells me with red exclamation marks "e.options is undefined", see screenshot1
Interestingly, the list of host groups will be shown at upper panel and also the panels ar enumerated for each entry, so its not an roles/rights nor authorization topic.

**Expected behavior**
The panels shows values

**Screenshots**
![grafik](https://github.com/alexanderzobnin/grafana-zabbix/assets/54597721/f7cbd942-96a8-44ca-8530-7cc4a15b5364)

**Network data**
Query: `{"datasourceId":1,"method":"hostgroup.get","params":{"output":["name","groupid"],"sortfield":"name","real_hosts":true}}`

Result: 
`{"result":[{"groupid":"7","name":"Hypervisors"},{"groupid":"2","name":"Linux servers"},{"groupid":"23","name":"Switches"},{"groupid":"22","name":"TrueNAS"},{"groupid":"26","name":"UPS"},{"groupid":"6","name":"Virtual machines"},{"groupid":"4","name":"Zabbix servers"},{"groupid":"24","name":"site_TST01"}]}`

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v9.5.2 (cfcea75916)   | 6.4.2  | 4.3.1                 |

Thanks for your help.

**Comment by jpcapone** [comment]
Did you ever get this fixed?  I have the same problem.

**Comment by ITfromHell** [comment]
Unfortunately no. And also no feedback or questions for details.
Do you use same versions?
I updated to Zabbix 6.4.8 and Grafana-Zabbix-Plugin 4.4.4, meanwhile.

**Comment by jpcapone** [comment]
> Unfortunately no. And also no feedback or questions for details. Do you use same versions? I updated to Zabbix 6.4.8 and Grafana-Zabbix-Plugin 4.4.4, meanwhile, but the problem is the same.

Grafana is version 10.2.2, Grafana-Zabbix-Plugin 4.4.4 and Zabbix is 6.4.10.  Let me know if you think of something we can try.
