### ISSUE TITLE
Item tag instead of Application

### ISSUE THREAD

**Issue by glebrodionov94** [grafana/grafana-zabbix#1643]
**Application instead of item tag**
Instead of item tag I see Application in type Triggers

**Expected behavior**
Item tag instead of Application

**Screenshots**
![image](https://github.com/alexanderzobnin/grafana-zabbix/assets/94922743/d6b93a24-85ce-4702-aae9-2ea55fbbc8bf)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
Grafana v9.5.2, Zabbix plugin 4.3.1, Zabbix 6.4.2

**Comment by alexanderzobnin** [comment]
Item tags are not supported by this kind of query, but at least application filter should be hidden if Zabbix version is not supporting it.
