### ISSUE TITLE
Deprecated plugin api

### ISSUE THREAD

**Issue by veshus** [grafana/grafana-zabbix#1654]
![image](https://github.com/alexanderzobnin/grafana-zabbix/assets/33095952/c451e67b-293c-49d8-a88a-583e76ad10b1)

Please make Zabbix problems panel compatible with grafana 10

**Comment by sympatheticmoose** [comment]
@veshus which version of the Zabbix plugin are you running? >4.3.0 should have no Angular dependency

**Comment by zoltanbedi** [comment]
This is already fixed.
