### ISSUE TITLE
Unable to view metrix older than 4 days with zabbix v2.2.6

### ISSUE THREAD

**Issue by kaidemae** [grafana/grafana-zabbix#1660]
Hello.
I'm using Grafana v9.5.3 with the Zabbix plugin v4.2.10.
I have added data sources for Zabbix v2.2.6 and v5.0.28.
However, I'm unable to view metrics older than 4 days when using the Zabbix v2.2.6 data source.
The data source for v5.0.28 works fine without any issues.
When I used Grafana v7.5.10, I was able to view any metrics of Zabbix v2.2.6 over a span of 1 week.

**Comment by krisavi** [comment]
Have you tried adjusting Trend values range value in data source settings?

**Comment by zoltanbedi** [comment]
I'm sorry but we can't support Zabbix version older than 5.
