### ISSUE TITLE
Datasource Problem Grafana 10.0.3

### ISSUE THREAD

**Issue by Dark-ZBX** [grafana/grafana-zabbix#1666]
Hi!

I have zabbix 6.0 and 6.2. And installed grafana 10.0.3,  adding allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app, alexanderzobnin-zabbix-datasource, alexanderzobnin-zabbix-triggers-panel, as well as removing Manifest.txt from plugin directory, restart services, etc.. but nothing works.
Does anyone have the solution? What versions of grafana do you recommend for zabbix 6.0, 6.2?

zabbix 6.2, zabbix 6.0, Grafana Plugin 4.3.1, Grafana OSS Windows Version v10.0.3

![image](https://github.com/grafana/grafana-zabbix/assets/74934252/b9736e3f-404b-45d8-b226-e3e14193b7ba)

![image](https://github.com/grafana/grafana-zabbix/assets/74934252/69703526-46fe-4d1a-84ff-6fe0bbe28d50)

![image](https://github.com/grafana/grafana-zabbix/assets/74934252/41cee5e7-8f22-49e2-b71d-9a9b5132fc0f)

regards!

**Comment by CeRberuS-FRA** [comment]
Hi erveryone,
I got same issue with fresh install of Grafana v10.0.2 (b2bbe10fbc), Zabbix plugin 4.3.1.
I just put this configuration on the conf file: 
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-triggers-panel
I am behind an enterprise proxy so i use http_proxy and https_proxy to get plugins.

When i try to declare a Zabbix DataSource i got "Plugin unavailable".

i got a an http code 503 to Zabbix-Api
 logger=context userId=1 orgId=1 uname=admin t=2023-08-02T09:25:27.0349185+02:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=[::1] time_ms=4 duration=4.2593ms size=46 referer=http://localhost:8000/datasources/edit/a6a17e88-811b-4664-8a2c-4926d8e36a25 handler=/api/datasources/:id/resources/*.

Maybe the declaration of the Zabbix-Api on the api is wrong?

If anyone have an idea it would be lovely.

Regards

**Comment by Dark-ZBX** [comment]
> Hi erveryone, I got same issue with fresh install of Grafana v10.0.2 (b2bbe10fbc), Zabbix plugin 4.3.1. I just put this configuration on the conf file: allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-app,alexanderzobnin-zabbix-datasource,alexanderzobnin-zabbix-triggers-panel I am behind an enterprise proxy so i use http_proxy and https_proxy to get plugins.
> 
> When i try to declare a Zabbix DataSource i got "Plugin unavailable".
> 
> i got a an http code 503 to Zabbix-Api logger=context userId=1 orgId=1 uname=admin t=2023-08-02T09:25:27.0349185+02:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=503 remote_addr=[::1] time_ms=4 duration=4.2593ms size=46 referer=http://localhost:8000/datasources/edit/a6a17e88-811b-4664-8a2c-4926d8e36a25 handler=/api/datasources/:id/resources/*.
> 
> Maybe the declaration of the Zabbix-Api on the api is wrong?
> 
> If anyone have an idea it would be lovely.
> 
> Regards

solved!

Reinstall grafana oss 10.0.3 and reinstall plugin 4.3.1 via CLI and works perfectly!

SO: Red Hat 8, Grafana 10.0.3, plugin 4.3.1.

Working for zabbix 6.4, 6.2, 6.0 and 5.0

Not works grafana for windows!

Regards!
