### ISSUE TITLE
Plugin Unavailable error Zabbix-6.4.5/6.0.20 Grafana Enterprise 10.0.3, plugin 4.3.1

### ISSUE THREAD

**Issue by buadams** [grafana/grafana-zabbix#1668]
[gafana_zabbix_error.docx](https://github.com/grafana/grafana-zabbix/files/12301261/gafana_zabbix_error.docx)

logger=context userId=1 orgId=1 uname=admin t=2023-08-09T14:36:01.834116424+04:00 level=warn msg="Plugin unavailable" error="plugin unavailable" traceID=
logger=context userId=1 orgId=1 uname=admin t=2023-08-09T14:36:01.83435872+04:00 level=error msg="Request Completed" method=POST path=/api/datasources/3/resources/zabbix-api status=503 remote_addr=10.10.10.10 time_ms=2 duration=2.383413ms size=46 referer=http://10.x.x.x:3000/datasources/edit/a0d23a38-bf14-4a5a-a112-233fe55c7251 handler=/api/datasources/:id/resources/*

Plugin unavailable error. Unable to add Zabbix as a data source. Details are in the attached file.Please help. Thanks

$grafana-server -v
Version 10.0.3 (commit: eb8dd72637, branch: HEAD)

$zabbix_server -V
zabbix_server (Zabbix) 6.4.5
Revision 6084b1dbbba 31 July 2023, compilation time: Jul 31 2023 12:52:40

I tried with 6.0 as well

 $ zabbix_server -V
zabbix_server (Zabbix) 6.0.20
Revision b60e269feb4 31 July 2023, compilation time: Jul 31 2023 15:22:39

$ php-fpm -v
PHP 8.0.27 (fpm-fcgi) (built: Jan  3 2023 16:17:26)
Copyright (c) The PHP Group
Zend Engine v4.0.27, Copyright (c) Zend Technologies

$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
```[tasklist]
### Tasks
```

**Comment by buadams** [comment]
Hello @alexanderzobnin; I appreciate your advice here. Many Thanks

**Comment by buadams** [comment]
I have tried hosting the Grafana instance on an external server, still have the same error. Moreover, I have noticed on network firewall logs that the Grafana server is not sending any traffic to the Zabbix server while doing save & test.

**Comment by buadams** [comment]
I have tried changing the default plugins directory of garafana to a different path. Then changed the config file (grafana.ini) to point (directory where grafana will automatically scan and look for plugins) to the new path. Then restarted the service, and it worked. Upon closer inspection, it was evident that the `/var/lib` directory was mounted with the noexec option, causing the original problem. This experience was an invaluable lesson that enabled me to resolve the issue and expanded my understanding of how system configurations can impact application functionality.

**Comment by NIBORSON** [comment]
Hello, i have de same problem and don't work with the redirect  plugins path.

My ZBX configuration:

Zabbix_server (Zabbix) 6.4.6
Grafana Server Version 10.0.3 (on the same server)
grafana-zabbix plugin 4.4.0

Tks
