### ISSUE TITLE
Error when click Dashboard after add datasouce Zabbix

### ISSUE THREAD

**Issue by leminhtu598** [grafana/grafana-zabbix#1669]
logger=context userId=1 orgId=1 uname=admin t=2023-08-13T17:33:40.247372994+07:00 level=error msg="Request Completed" method=GET path=/api/plugins/alexanderzobnin-zabbix-datasource/dashboards status=500 remote_addr=192.168.113.52 time_ms=46 duration=46.149551ms size=58 referer=http://192.168.113.8:3000/connections/datasources/edit/f688f883-f54c-457b-a7cb-43ba5d87f464/dashboards handler=/api/plugins/:pluginId/dashboards/

**Comment by aaujon** [comment]
Hi,
Same here en 4.4.0, log is :
`logger=context userId=1 orgId=1 uname=admin t=2023-08-24T10:30:45.405430794+02:00 level=error msg="Failed to get plugin dashboards" error="open /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/dashboards/zabbix_system_status.json: no such file or directory" remote_addr=172.18.32.28 traceID=`

**Comment by aaujon** [comment]
Same as https://github.com/grafana/grafana-zabbix/issues/1611
