### ISSUE TITLE
Filtering Items by Applications didn't  work

### ISSUE THREAD

**Issue by keminc** [grafana/grafana-zabbix#1671]
**Describe the bug**
Filtering Items by Applications didn't  work on dashboard panels.

**Expected behavior**
I can put any data to the Application field and it doesn't affect on the item list on the panel.

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/37383165/84289043-1c56-48b7-9e74-6f76062eead8)
![image](https://github.com/grafana/grafana-zabbix/assets/37383165/39705567-9265-44d8-bcd3-1b7705575de5)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | --------- | ------------------------- |
| 9.4.7    | 5.0.36     | 4.3.1                             |

**Comment by alexanderzobnin** [comment]
I thinks it's the same as #1597
