### ISSUE TITLE
update node-related things to a newer LTS version

### ISSUE THREAD

**Issue by gabor** [grafana/grafana-zabbix#1674]
certain files refer to node16, which is going to be end-of-life soon, we should use newer node versions there:
- https://github.com/grafana/grafana-zabbix/blob/518d8a13f80c7a1ce4ef786f7804b501e8d6df2a/.nvmrc#L1
- https://github.com/grafana/grafana-zabbix/blob/518d8a13f80c7a1ce4ef786f7804b501e8d6df2a/package.json#L124-L126
- `.github/workflows`

**Comment by alexanderzobnin** [comment]
Yes, it's a bit of a pain, tried it, but got build broken. Once we moved everything to drone, maybe now it will work.

**Comment by zoltanbedi** [comment]
this is fixed in https://github.com/grafana/grafana-zabbix/pull/1692
