### ISSUE TITLE
delta() function not working

### ISSUE THREAD

**Issue by tm-pieman** [grafana/grafana-zabbix#1676]
I have:
* zabbix 6.0.7
* Grafana 10.1.0
* Zabbix Plugin 4.4.0

Zabbix stores a numeric incrementing metric. In the dashboard we use the delta() function, which does not work in the latest version, does not produce a result, although in the old version of the plugin 4.1.5 it works as it should.

**Comment by alexanderzobnin** [comment]
Hi! Could you explain it a bit more, what exactly result looks like? I briefly tested on the latest version (4.4.1) and it seems to be working correctly.

**Comment by tm-pieman** [comment]
Hi @alexanderzobnin.
Previously, I used the `delta()` function to display the changes between the current value and the previous value. But in the latest version, I discovered that it does not return the result at all.
Found how to fix this, you need to put a checkbox in **Options** near the value of **Disable data argument**

Thank you for your work and for your reply.

Дублирую на Русском:

> Здравствуйте, @alexanderzobnin
> Раньше я использовал функцию `delta()` для отображения измений между текущим и предыдущим значением. Но в последней версии обранужил что она вообще не возвращает результат.
> Нашёл как пофиксить это, нужно поставить чекбокс в **Options** у значения **Disable data argument**
> 
> Спасибо за вашу работу и что ответили.
