### ISSUE TITLE
Error querying Zabbix version (request failed, status: 404 Not Found)

### ISSUE THREAD

**Issue by leitones** [grafana/grafana-zabbix#1680]
My Zabbix at Oracle have IP 10.0.30.30 and running at port 8080 and I can't do the integration with Grafana, already tried with :8080 without :8080 and this error still is running, can someone help me? I know that's something stupid that Im doing.

[https://imgur.com/a/qtZugpm](url)
![Sem título](https://github.com/grafana/grafana-zabbix/assets/104843060/61e627d4-685a-4594-88a6-55c971c09063)

logger=plugin.alexanderzobnin-zabbix-datasource t=2023-09-02T18:18:39.611929862-03:00 level=error msg="Error querying Zabbix version" error="request failed, status: 404 Not Found"

logger=plugin.alexanderzobnin-zabbix-datasource t=2023-09-02T18:18:39.613040185-03:00 level=error msg="Zabbix API request error" error="request failed, status: 404 Not Found"

**Comment by LivingLegendcz** [comment]
What result did you received when you tried to call Zabbix API in another application ( e.g. curl, postman etc)?

**Comment by adrianlzt** [comment]
Probably you have zabbix-web exposed in port :8080 wihtout the "zabbix/" part.
So maybe the correct endpoint is http://10.0.30.30:8080/api_jsonrpc.php

**Comment by artisan1-k** [comment]
i fixed, thx @adrianlzt was :8080 without zabbix.

**Comment by zoltanbedi** [comment]
Thanks for helping out @adrianlzt. I'm going to close the issue as it seems to be resolved.
