### ISSUE TITLE
Colour Overrides break after upgrading the plugin version

### ISSUE THREAD

**Issue by gwdawson** [grafana/grafana-zabbix#1687]
> 1. i found its easier to reproduce on hosted grafana because you can easily update plugin versions
> 2. this bug is reproducible both ways, on version "upgrade" and "downgrade"

### Steps to reproduce:
1. Install the Zabbix plugin on an earlier version.
2. Create a dashboard panel with some colour overrides
   - Zabbix datasource with TimeSeries Panel
   - In this example i used the FillOpacity override
     ![Image](https://github.com/grafana/grafana-zabbix/assets/34524710/d05e9258-be8b-4efd-95db-03c8699d471f)
3. Upgrade the plugin version
   - Check the dashboard panels, the overrides are broken
     ![Image](https://github.com/grafana/grafana-zabbix/assets/34524710/9a19851d-d8fa-4569-8ac7-577bb6270e04)

---

### Looking deeper:

- i have found that if you use the `setAlias` function in zabbix, the override doest break after upgrading
- you can see that after upgrading, the reason the override breaks is because it doesn't detect the field name hence the `(Not found)`
- ![Image](https://github.com/grafana/grafana-zabbix/assets/34524710/a62fd61b-3acb-4c8e-b7df-2918f3261193)

**Comment by gabor** [comment]
- exporting a dashboard-json-with-field-override from `4.2.0` and importing into `4.3.0`  does work (override applies)
- exporting a dashboard-json-with-field-override from `4.3.0` and importing into `4.4.0`  does not work (override does not apply)

this seems logical because the "calculated" field-name is `Zabbix server: something` for `4.2.0` and `4.3.0`, and it's `something` for `4.4.0`.

**Comment by gabor** [comment]
the change in https://github.com/grafana/grafana-zabbix/commit/e33812427ed650e65f60088a4e59105587dd2dd0 may be relevant here.

**Comment by gabor** [comment]
i do not think we can do anything to improve the situation here, changing the dataframe format again would just make more problems. 
for people having this problem a possible workaround is to use aliases, those will guarantee that the name is fixed.
