### ISSUE TITLE
PGP key that should be used for encrypt a vulnerability report, expired 7 months ago

### ISSUE THREAD

**Issue by andrey-podko** [grafana/grafana-zabbix#1689]
Your security policy requires a encrypt message with your PGP key, but it's expired ! 

pub   rsa4096 2022-02-03 [SC] [expires: 2024-02-03]
      225E6A9BBB15A37E95EB6312C66A51CCB44C27E0
uid           [ unknown] Grafana Labs Security Team <security@grafana.com>
**sub   rsa4096 2022-02-03 [E] [expired: 2023-02-03]**

Can you fix it ASAP please ? Because I'm going report it directly as Issue
I'm sorry, but any policy have a sense while it works :)

**Comment by Conall-Grafana** [comment]
Hi andrey,

I see the security report is in progress and the security issue has been linked.

Our security team plans to update the expired PGP subkey this week, I'l confirm once that's completed.

**Comment by zoltanbedi** [comment]
Thanks for letting us know @andrey-podko. I'm going to close this issue as this is something that we already took care of.

**Comment by andrey-podko** [comment]
@zoltanbedi  are you sure ? ;) 

I tried to gpg --refresh-keys,
also remove and import key again. Subkey on ubuntu keyserver is still expired :)

**Comment by zoltanbedi** [comment]
Sorry yes this not yet extended but is something that we will do soon.

**Comment by Conall-Grafana** [comment]
Hi, They key has now been extended to expire in 2026.

an example of receiving the extended key via the gpg command line is below: 
`gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 225e6a9bbb15a37e95eb6312c66a51ccb44c27e0`

you may then verify the outcome using `gpg --list-sigs`

![image](https://github.com/grafana/grafana-zabbix/assets/115151870/eb8a0b21-5cb0-4eca-9006-0944b5c9692d)


Kind regards,
