### ISSUE TITLE
gRPC opts.GRPCSettings.MaxReceiveMsgSize too small - "NetworkError trying to fetch resource"

### ISSUE THREAD

**Issue by pyite** [grafana/grafana-zabbix#1720]
I have some power users who create graphs with many millions of data points.

Sometimes their graphs cause a problem where the browser pops up a red error box saying something like "NetworkError trying to fetch resource"

In 4.1.5 I traced this down to gRPC limiting the maximum message size to 16M.  At the time, the gRPC vendor code was part of the Makefile so I just increased the number in vendor/github.com/grafana/grafana-plugin-sdk-go/backend/serve.go.

In 4.2.10, the vendor code is no longer part of the build system so I had to figure out how to do it the "right way".  I seem to have fixed it by adding the following GRPCSettings value to the file pkg/plugin.go.  Does this look like the correct way to change the maximum receive message size:

        err := backend.Serve(backend.ServeOpts{
                CallResourceHandler: httpResourceHandler,
                QueryDataHandler:    ds,
                CheckHealthHandler:  ds,
                GRPCSettings: backend.GRPCSettings{MaxReceiveMsgSize: 67108864},
        })

So far it seems to have fixed the problem.  I'll keep an eye on it this week to see if it's really fixed.

If so, would it be possible to either add a larger number as the default or to make the value configurable?  I currently have to set Grafana to developer mode so it will accept my unsigned change.

On a related note - I have one Firefox instance that still has the problem.  I created a new user on this system and the problem does not happen.  Is there any code that is downloaded to the browser that I need to clear out to force this change through?

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.0.2   | 6.4.4  | 4.2.10                 |

**Comment by zoltanbedi** [comment]
> Does this look like the correct way to change the maximum receive message size
yes that is the way to do that @pyite.
