### ISSUE TITLE
Support for host_tag

### ISSUE THREAD

**Issue by clontarfx** [grafana/grafana-zabbix#1732]
It would be nice to be able to filter the Zabbix datasource by host_tag. This allows for dashboards to be filtered to relevant topics of interest, for example a vSphere tag that has been added to a discovered virtual machine or datastore.

This would solve a related Zabbix issue where it is not possible to add items discovered by VMware LLD to an ad-hoc host group.

I imagine this should function in a similar way that item_tag does.

**Comment by zoltanbedi** [comment]
Duplicate of #1651
