### ISSUE TITLE
I need help creating sorting logic in grafana

### ISSUE THREAD

**Issue by BadSpider1** [grafana/grafana-zabbix#1736]
Greetings,

I am seeking assistance with the development of a system in Grafana, for which I currently lack the requisite knowledge. I have configured Zabbix as the data source for my dashboards. Specifically, in the dashboard under consideration, I am employing rows to repeat hosts. These hosts are radio devices, identified by the street on which they are located and the corresponding secondary radio used for two-way communication.

My objective is to display only the source radio for each pair, and their sole distinguishing feature is their respective IP addresses. To illustrate, if the IP address of the first radio is 10.10.100.1, the IP address of the second radio in the pair is [10.10.100.2](https://10.10.100.2/). The IP address is an item. My challenge lies in ensuring that only the first radios are displayed, as these radio pairs lack any inherent linkage.

Is there a method or solution available to help me accomplish this goal?

**Comment by isaqueprofeta** [comment]
Should be closed, it's not a Grafana issue, should be addressed on Zabbix  side.

Since you already have the “IP Address” as an Item, you can set a Item Tag of “source radio” at Zabbix side. Then, at Grafana’s side you just filter it using the field for Tag at the query builder.

**Comment by zoltanbedi** [comment]
Hey @BadSpider1 please use [our forum](https://community.grafana.com/) for asking questions. Thanks to @isaqueprofeta I think you have an idea now.
