### ISSUE TITLE
Current state of the dashboards

### ISSUE THREAD

**Issue by jpcapone** [grafana/grafana-zabbix#1738]
Can anyone tell me if there is a way to grab the dashboards that you should be able to get from the Dashboards tab of the zabbix plugin?  Currently, I get the error `Failed to get plugin dashboards` when i click that tab.  I see suggestions that you can copy the dashboards folder into the datasources folder but I am unable to find the dashboards folder anywhere within the container.  When I grab the random json for either of the 3 dashboards that should be available from the Dashboards tab I get mixed results with some panels displaying the no data error.  Any suggestions or assistance would be greatly appreciated.

found a solutions right after posting this: 
from the grafana command line 
`grafana-cli plugins remove alexanderzobnin-zabbix-app`
restart
`grafana-cli plugins install alexanderzobnin-zabbix-app 4.2.10`

Now I am getting no data for the dashboard panels.
any suggestions?

**Comment by zoltanbedi** [comment]
This was fixed in https://github.com/grafana/grafana-zabbix/pull/1727 but not released yet.

**Comment by jpcapone** [comment]
> This was fixed in #1727 but not released yet.

Is there anyway i can help test it out?
