### ISSUE TITLE
Zabbix Plugin Failed after Grafana Upgrade to 10.2.0

### ISSUE THREAD

**Issue by cameronw1996** [grafana/grafana-zabbix#1741]
**Describe the bug**
After upgrading Grafana to 10.2.0 the Zabbix Plugin failed to load. However it did work for around 6hrs. I now get this error message and the date source config page does not work. 

_Zabbix plugin failed
Error: 404 , loading https://mydomain/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js?_cache=1699866657534 (SystemJS Error#7 https://github.com/systemjs/systemjs/blob/main/docs/errors.md#7)_

**Screenshots**
![grafana 1](https://github.com/grafana/grafana-zabbix/assets/1197720/319a32dd-dc30-44d0-b4af-d05e78d16475)
![grafana 2](https://github.com/grafana/grafana-zabbix/assets/1197720/efbf49cb-b3af-42cb-acd6-17d3df2f819a)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 10.2.0   | 6.0.12  | 4.4.3 |

**Comment by zoltanbedi** [comment]
Hey @cameronw1996,
can you show us your grafana logs?

**Comment by cameronw1996** [comment]
@zoltanbedi please see below last few lines from Grafana log:

`logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:16:23.345914703Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:16:23.346009206Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.26775ms size=132 refer>logger=context userId=14 orgId=1 uname=Michael.Ryan@lothianbroadband.com t=2023-11-13T10:16:26.775909309Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=89.32.89.65 time_ms=10 duration=10.7>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:18:23.319808459Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:18:23.319912964Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.092843ms size=132 refe>
logger=cleanup t=2023-11-13T10:20:10.280159601Z level=info msg="Completed cleanup jobs" duration=21.252732ms
logger=grafana.update.checker t=2023-11-13T10:20:10.341197192Z level=info msg="Update check succeeded" duration=8.121118ms
logger=plugins.update.checker t=2023-11-13T10:20:10.38657507Z level=info msg="Update check succeeded" duration=38.322601ms
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:20:25.64347694Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=185.196.204.178 time_ms=1 duration=1.556561ms size=0 referer= h>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:20:27.749825807Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:20:27.749922511Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.29825ms size=132 refer>logger=context userId=37 orgId=1 uname=Lauren.Mcfadyen@lothianbroadband.com t=2023-11-13T10:20:50.861301228Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=89.32.89.65 time_ms=10 duration=1>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:21:26.905828466Z level=info msg="Request Completed" method=GET path=/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js status=404 remote_addr=185>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:22:27.384926461Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:22:27.385028965Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.576862ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:24:27.254208241Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:24:27.254286644Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.096942ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:26:29.492600965Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=185.196.204.178 time_ms=1 duration=1.664265ms size=0 referer= >logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:26:31.520332124Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:26:31.520837944Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.54346ms size=132 refer>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:27:30.61373769Z level=info msg="Request Completed" method=GET path=/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js status=404 remote_addr=185.>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:28:30.972478294Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:28:30.972571897Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.401455ms size=132 refe>logger=context userId=14 orgId=1 uname=Michael.Ryan@lothianbroadband.com t=2023-11-13T10:29:40.52778891Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=89.32.89.65 time_ms=2 duration=2.8378>
logger=cleanup t=2023-11-13T10:30:10.286542345Z level=info msg="Completed cleanup jobs" duration=27.274765ms
logger=grafana.update.checker t=2023-11-13T10:30:10.349796415Z level=info msg="Update check succeeded" duration=16.958862ms
logger=plugins.update.checker t=2023-11-13T10:30:10.382228481Z level=info msg="Update check succeeded" duration=33.718517ms
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:30:30.890820867Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:30:30.890912371Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=0 duration=987.738µs size=132 refer>
logger=infra.usagestats t=2023-11-13T10:31:24.252956491Z level=info msg="Usage stats are ready to report"
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:32:33.169517672Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=185.196.204.178 time_ms=1 duration=1.51856ms size=0 referer= h>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:32:35.165519464Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:32:35.165613568Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.259649ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:33:34.478195742Z level=info msg="Request Completed" method=GET path=/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js status=404 remote_addr=185>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:34:16.993037529Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=185.196.204.178 time_ms=4 duration=4.573681ms size=0 referer= >
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:34:34.60361108Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:34:34.603702984Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.205247ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:36:34.651605899Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:36:34.651681302Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.164046ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:38:37.32593541Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=185.196.204.178 time_ms=1 duration=1.619463ms size=0 referer= h>
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:38:39.02708452Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:38:39.027601841Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.714767ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:39:38.279316465Z level=info msg="Request Completed" method=GET path=/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js status=404 remote_addr=185>
logger=cleanup t=2023-11-13T10:40:10.281787965Z level=info msg="Completed cleanup jobs" duration=22.843575ms
logger=grafana.update.checker t=2023-11-13T10:40:10.341067137Z level=info msg="Update check succeeded" duration=8.531127ms
logger=plugins.update.checker t=2023-11-13T10:40:10.37687361Z level=info msg="Update check succeeded" duration=28.690299ms
logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:40:38.493638306Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:40:38.493725309Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.242649ms size=132 refe>logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:42:38.502230444Z level=info msg="Bad request" error="[query.duplicateRefId] multiple queries using the same RefId is not allowed" remote_addr=185.196.204.178 traceID=logger=context userId=3 orgId=1 uname=cameron2 t=2023-11-13T10:42:38.502326047Z level=info msg="Request Completed" method=POST path=/api/ds/query status=400 remote_addr=185.196.204.178 time_ms=1 duration=1.074942ms size=132 refe>

`

**Comment by zoltanbedi** [comment]
@cameronw1996 can't see anything related to the plugin. Usually this error happens when the plugin is not installed properly. The error I was looking for is in the beginning of the logs when grafana starts

**Comment by cameronw1996** [comment]
@zoltanbedi Should i restart grafana to see if we can see the error?

**Comment by zoltanbedi** [comment]
yeah, that would help

**Comment by cameronw1996** [comment]
Rebooting the server seems to have worked. I'll monitor it and see how it performs

**Comment by cameronw1996** [comment]
Seems stable after 24hrs. Will close for now
