### ISSUE TITLE
Zabbix plugin v4.4.4  doesn't appears in list of datasources

### ISSUE THREAD

**Issue by goomicson** [grafana/grafana-zabbix#1756]
Hi!

I've installed the Zabbix plugin for my Grafana, but it does not appear in the list of available datasources.
The installation process ends successfully with the following message:

```
> grafana-cli plugins install alexanderzobnin-zabbix-app
✔ Downloaded and extracted alexanderzobnin-zabbix-app v4.4.4 zip successfully to /var/lib/grafana/plugins/alexanderzobnin-zabbix-app
```

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.`

To fix it, I tried adding the parameter:
```
In /etc/grafana/grafana.ini:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource

In /usr/share/grafana/conf/defaults.ini:
allow_loading_unsigned_plugins = alexanderzobnin-zabbix-datasource
```

However, it had no effect.

I'm using Grafana v10.1.5.
```
grafana-server -v                                                                                                                                                                     
Version 10.1.5 (commit: 849c612fcb, branch: HEAD) 
```

**Comment by DmitryNX** [comment]
Hi, I faced the same problem. 
In my case I have found a temporary solution:

1. You need to open `plugin.json` in Zabbix plugin directory
`.../grafana/plugins/alexanderzobnin-zabbix-app/plugin.json`
or even before the plugin installation change one in plugin zip archive.

2. Remove the following line at the beginning of the file.
`"grafanaVersion": "9.3",`

I am not sure that is good way but it works for me.

**Comment by zoltanbedi** [comment]
@goomicson did you restart your grafana?

**Comment by goomicson** [comment]
> @goomicson did you restart your grafana?

Of course. I've tried `service grafana-server restart`. Also tried to reinstall plugin and rebooting the whole VM.
