### ISSUE TITLE
Direct DB Connection for postgres fails in grafana 10.2.3 (works in 10.2.2)

### ISSUE THREAD

**Issue by Dennisik** [grafana/grafana-zabbix#1764]
After updating Grafana from version 10.1.6 to 10.2.3, there is no option to select a PSQL source in Direct DB Connection.
On versions 10.1.x everything works as it should, but on version 10.2.x it does not work.

![image](https://github.com/grafana/grafana-zabbix/assets/75666397/00c5d88a-6264-48d0-b559-4eb72224fc56)
![image](https://github.com/grafana/grafana-zabbix/assets/75666397/e036dcdb-9f85-4386-bcb4-8867996581fc)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.2.3   | 6.4.5  | 4.4.1                 |

**Comment by rohanrajnv** [comment]
I am also facing the same issue

**Comment by reldred** [comment]
Yeap. Just migrated my grafana from a standalone docker server to my new production swarm cluster which pulled a fresh grafana docker image and I've lost the ability to talk to PostGres. Keen to hear what the go is :-D

**Comment by Glafkon** [comment]
Same issue. Updating Grafana to 10.2.3 from 10.2.2 and get the error "Could not connect to given url" - if "Enable Direct DB Connection" is activating

**Comment by javivu** [comment]
Same issue in my side.

Grafana | Zabbix | Grafana-Zabbix Plugin|
-- | -- | --
10.2.3 | 6.4.10 | 4.4.4
In my case, with Grafana PostgreSQL Data Source.

**Comment by kaellego** [comment]
I have the same problem. Here my environment is

| Grafana | Zabbix | Grafana-Zabbix Plugin |
|----------|--------|--------------------------|
| 10.2.3 | 4.4.4 | 4.4.4|

only MySQL appears, but I need the PostgreSQL Data Source

**Comment by GustelDE** [comment]
Same here, the PostgresDB-Data-Source shows simply not up in the list and if already selected "Could not connect to given url".

Grafana: 10.2.3
Zabbix: 6.4.10
Grafana-Zabbix Plugin: 4.3.1 and 4.4.4

**Comment by daFlo** [comment]
+1

Grafana: 10.2.3
Zabbix: 6.4.10
Grafana-Zabbix Plugin: 4.4.4

**Comment by EYEVO** [comment]
Same here

Grafana: 10.2.3
Zabbix: 6.4.10
Grafana-Zabbix Plugin: 4.4.4

**Comment by gabor** [comment]
the fix is live in the newest zabbix release (4.4.5)
