### ISSUE TITLE
I can´t add zabbix as data source (Skipping loading plugin due to problem with signature)

### ISSUE THREAD

**Issue by carlospulido-ciranda** [grafana/grafana-zabbix#1767]
Zabbix 6.2 on Debian 10.2
Grafana v10.0.1 local on Windows Server 2012

I'am trying to add Zabbix as data source but i received the following errors on log file after installation 

logger=plugin.loader t=2023-12-27T11:20:03.2237061-03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=alexanderzobnin-zabbix-triggers-panel status=unsigned
logger=plugin.loader t=2023-12-27T11:20:03.225706-03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=digrich-bubblechart-panel status=unsigned
logger=plugin.loader t=2023-12-27T11:20:03.2267064-03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=jeanbaptistewatenberg-percent-panel status=unsigned
logger=plugin.loader t=2023-12-27T11:20:03.2287064-03:00 level=warn msg="Skipping loading plugin due to problem with signature" pluginID=alexanderzobnin-zabbix-datasource status=unsigned

I've already added this config in the .ini file

[plugins]
enable_alpha = false
app_tls_skip_verify_insecure = false
#Enter a comma-separated list of plugin identifiers to identify plugins to load even if they are unsigned. Plugins with modified signatures are never loaded.

**_allow_loading_unsigned_plugins = alexanderzobnin-zabbix-app, digrich-bubblechart-panel, alexanderzobnin-zabbix-triggers-panel, alexanderzobnin-zabbix-datasource, alexanderzobnin-zabbix-triggers-panel_**

#Enable or disable installing / uninstalling / updating plugins directly from within Grafana.
plugin_admin_enabled = true
plugin_admin_external_manage_enabled = false
plugin_catalog_url = https://grafana.com/grafana/plugins/
#Enter a comma-separated list of plugin identifiers to hide in the plugin catalog.
plugin_catalog_hidden_plugins =
#Log all backend requests for core and external plugins.
log_backend_requests = false
#Force download of public key for verifying plugin signature on startup.
enforce_public_key_download = false

![zab n aparece](https://github.com/grafana/grafana-zabbix/assets/77060251/de4519d1-cee0-4706-bce0-b04e99302896)

 R![zabb](https://github.com/grafana/grafana-zabbix/assets/77060251/9bd6e9a9-fb39-4caf-ae48-0eaf61627b53)

**Comment by carlospulido-ciranda** [comment]
After changing this parameter, now i am able to add zabbix as that source

APP_MODE=development

But i use Grafana as a production service and its showing me this message 
Unsigned
![zabbixxxxx](https://github.com/grafana/grafana-zabbix/assets/77060251/304d1588-9e34-430e-9654-3f12df082320)

**Comment by hardwareadictos** [comment]
Same issue here, had to add APP_MODE=development to my env file to be able to use Zabbix Plugin

**Comment by zoltanbedi** [comment]
Hey there this was in issue in grafana. There will be a new version 10.3.0 out soon with the fix. https://github.com/grafana/grafana/issues/78700
