### ISSUE TITLE
Zabbix not appearing in datasources (plugin version: 4.4.5)

### ISSUE THREAD

**Issue by YuriTAngelico** [grafana/grafana-zabbix#1775]
**Describe the bug**
Zabbix not appearing in datasources (plugin version: 4.4.5)

Steps of installation:

1:

```
root@*********:/home/*******# grafana-cli plugins install alexanderzobnin-zabbix-app
✔ Downloaded and extracted alexanderzobnin-zabbix-app v4.4.5 zip successfully to /var/lib/grafana/plugins/alexanderzobnin-zabbix-app

Please restart Grafana after installing or removing plugins. Refer to Grafana documentation for instructions if necessary.
```

2:

`root@*********:/home/*******# systemctl restart grafana-server.service`

**Expected behavior**
Zabbix datasource appear in the datasources screen

**Screenshots**

After installation I did changed the files **/usr/share/grafana/conf/defaults.ini** and **/etc/grafana/grafana.ini **. I changed the line “_allow_loading_unsigned_plugins_” with this: “_alexanderzobnin-zabbix-datasource_”. Then I restart the services and did not worked.

Logs from grafana (using command "sudo cat /var/log/grafana/grafana.log | grep zabbix") :

```
logger=plugin.alexanderzobnin-zabbix-datasource t=2024-01-11T14:01:19.841218546-03:00 level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/gpx_zabbix-plugin_linux_amd64 id=3546 error="signal: terminated"
logger=plugins.registration t=2024-01-11T14:01:21.08876996-03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-app
logger=plugins.registration t=2024-01-11T14:01:21.088835961-03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-triggers-panel
logger=plugins.registration t=2024-01-11T14:01:21.088891062-03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-datasource
```

![image](https://github.com/grafana/grafana-zabbix/assets/41388505/6ff944f9-6a12-430e-9646-2c5dbaa57014)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| Grafana v10.2.3 | 6.4 | 4.4.5 |

OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-91-generic x86_64)

**Comment by YuriTAngelico** [comment]
If more logs needed please ask me.

**Comment by YuriTAngelico** [comment]
We manage to make it work but is reported as not supported:

![image](https://github.com/grafana/grafana-zabbix/assets/41388505/f06f083a-3afc-4a75-b0b4-4128c1bb3547)

**Comment by YuriTAngelico** [comment]
We manage to upgrade the plugin and now it is working. It was disabled in the plugin page.

**Comment by mahdi-saberi** [comment]
same problem in Grafana Version 11.3.0 
alexanderzobnin-zabbix-app @ 4.5.6


`logger=plugin.alexanderzobnin-zabbix-datasource t=2024-10-27T09:57:19.062740607Z level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource/gpx_zabbix-datasource_linux_amd64 id=2581 error="signal: terminated"
`

there is no more data in grafana.log about zabbix problem
