### ISSUE TITLE
Services/SLA with Zabbix 5

### ISSUE THREAD

**Issue by OCrylic** [grafana/grafana-zabbix#1779]
Hi,

I am currently running with Zabbix 6 and Grafana 9.4, plugin 4.3.1.
Working with services and SLA works well.
However, on this Grafana, I also have the need to get SLA value from a Zabbix 5 but I get the following error: "Method not found. Incorrect API "sla"".
Does this mean that since version 4.3.0, plugin does not support Zabbix 5 services ?
If this is the case iIs there a way to adapat the query like for item tag and item application according Zabbix version ?

**Comment by zoltanbedi** [comment]
Hi @OCrylic,

It does meant that yes and sadly you can't adapt the query.
