### ISSUE TITLE
Zabbix api for grafana

### ISSUE THREAD

**Issue by mricoteja** [grafana/grafana-zabbix#1780]
hello, I'm using the latest version of zabbix and grafana and when it comes to implement it I can not because the url of zabbix example.com/zabbix/api_jsonrpc.php  tells me that it does not exist, I tried with the url / api_jsonrpc.php without the zabbix and neither, I also tried with 
url:8080/api_jsonrpc.php
url:8080/zabbix/api_jsonrpc.php
and I get that it does not exist, 
do you know what it can be?

Thank you 
![image](https://github.com/grafana/grafana-zabbix/assets/154325088/e397bf6f-f7ab-420e-a09f-1eca8b279d21)

**Comment by zoltanbedi** [comment]
We don't know where your zabix API is located.
