### ISSUE TITLE
msg="plugin process exited" ... error="signal: terminated" 

### ISSUE THREAD

**Issue by img0043** [grafana/grafana-zabbix#1781]
Grafana: 10.2.1, 10.2.3  | Grafana-Zabbix Plugin 4.3.1, 4.4.5 | 
```
logger=plugin.alexanderzobnin-zabbix-datasource t=2024-01-19T20:51:34.816336388+03:00 level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/gpx_zabbix-plugin_linux_amd64 id=9054 error="signal: terminated"
logger=plugins.registration t=2024-01-19T20:51:35.312771716+03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-app
logger=plugins.registration t=2024-01-19T20:51:35.31817292+03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-triggers-panel
logger=plugins.registration t=2024-01-19T20:51:35.318194465+03:00 level=info msg="Plugin registered" pluginId=alexanderzobnin-zabbix-datasource

```

All 3 modules write that they are registered, but Grafana catches an error  msg="plugin process exited" ... error="signal: terminated"
I found the previous discussion threads - I rolled back to the old versions, but the error is the same.

Does anyone know how to solve the problem now?

**Comment by zoltanbedi** [comment]
Can you please let us know how to reproduce this issue?

**Comment by mahdi-saberi** [comment]
i get this in 
`
grafana version 11.3 
grafana-zabbix 4.5.6
`

`logger=plugin.alexanderzobnin-zabbix-datasource t=2024-10-27T10:19:29.303693783Z level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource/gpx_zabbix-datasource_linux_amd64 id=2717 error="signal: terminated"`

**Comment by eldar-safin** [comment]
I see the plugin in Administration / Plugins and data and enabled it. But there is no plugin in Datasource.
In /var/log/grafana/grafana.log:
`logger=plugin.alexanderzobnin-zabbix-datasource t=2024-12-28T12:16:17.897730384+03:00 level=error msg="plugin process exited" plugin=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource/gpx_zabbix-datasource_linux_amd64 id=2213503 error="signal: terminated"
`
Grafana v11.2.2
alexanderzobnin-zabbix-app v4.6.0
RED OS MUROM (7.3.4)
