### ISSUE TITLE
Grafana cloud refuses to reset Zabbix API token

### ISSUE THREAD

**Issue by diasdmhub** [grafana/grafana-zabbix#1796]
## Versions

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| --- | --- | --- |
| Cloud | 6.4.12 | 4.4.5 |

<BR>

## The issue
I have a Grafana Cloud instance with a Zabbix plugin installed.
I have configured the Zabbix data-source and it worked fine.

Now, I need to change the Zabbix API token, but Grafana won't reset the token.
It shows the token as configured, but the reset button does nothing.
![image](https://github.com/grafana/grafana-zabbix/assets/67486897/a02b6dfd-d4a8-4afe-95b8-45eab7ff9197)

I was able to reconfigure the Zabbix data-source with a user and password, but the API token just won't to reset.
What could be wrong?

<BR>

## Expectations
A correct token reset.

**Comment by diasdmhub** [comment]
@zoltanbedi, I'm still unable to reset the token. Nothing happens when I click the reset button.

**Comment by zoltanbedi** [comment]
@diasdmhub sorry this is not yet released. I'll cut a release today.

**Comment by diasdmhub** [comment]
@zoltanbedi, I'm still unable to reset the token. Any news?

**Comment by zoltanbedi** [comment]
@diasdmhub have you updated the plugin to 4.4.6?

**Comment by diasdmhub** [comment]
After updating the plugin and updating the Grafana instance, I was able to reset the token.
Thank you.

**Comment by zoltanbedi** [comment]
Thanks for letting us know @diasdmhub and also reporting it in the first place.
