### ISSUE TITLE
I cannot delete a function (for example, transform -1) by clicking the x

### ISSUE THREAD

**Issue by jars99** [grafana/grafana-zabbix#1801]
I added a transform function to my query, but now I want to delete it.  I click on "scale" then I see a popup that look something like this: "<?x>".   

When I try to click the x, the popup disappears, and the function is still there.   I've had this problem for months, and am finally reporting it. 

I'm using Chrome on MacOS.  I'm running Grafana v10.2.0 with zabbix plugin 4.4.6

**Comment by zoltanbedi** [comment]
I just tried this out and the x removed the function. Grafana 10.2.0 in Chrome. Can you try to reproduce this with firefox? or with extensions disabled?
