### ISSUE TITLE
How to see hostname + metric in legend?

### ISSUE THREAD

**Issue by shab2** [grafana/grafana-zabbix#1804]
Hello!
Grafana v10.4.0, Zabbix plugin 4.4.6
What I should exactly do for see hostname into string legend?
Now I have in one chart data from 2 hosts. I want see hostname + metric name in legend  
Legend: <myhost1> cpu wait <myhost2> cpu wait
Thank you

**Comment by shab2** [comment]
I dont should spend my time to change function setalias to $__zbx_host_name $__zbx_item_name.
Please, resolve it. Thanks

**Comment by bernardolankheet** [comment]
> Hello! Grafana v10.4.0, Zabbix plugin 4.4.6 What I should exactly do for see hostname into string legend? Now I have in one chart data from 2 hosts. I want see hostname + metric name in legend Legend: cpu wait cpu wait Thank you

What panel did you used?

**Comment by zoltanbedi** [comment]
Closing this issue due to lack of response; feel free to reopen if further input or clarification is provided.
