### ISSUE TITLE
"Zabbix Problems Panel" display problems

### ISSUE THREAD

**Issue by dunehunter** [grafana/grafana-zabbix#1806]
**Describe the bug**
Zabbix problem panel" table collapses.

**Expected behavior**
It should display correctly like this:
![image](https://github.com/grafana/grafana-zabbix/assets/53830992/d0e114bb-42d4-47a0-b3be-446f9c4fef26)

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/53830992/75bc12af-3cbe-43fc-9c58-bcbe037d327c)

**Network data**

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 10.2.3   | 5.4  | 4.4.5                 |

**Comment by dunehunter** [comment]
I tried to update the plugin to 4.4.6 and still got this issue, anyone can take a look? @alexanderzobnin

**Comment by dunehunter** [comment]
Bump, any feedback?

**Comment by bsoler-tpg** [comment]
I'm having the same problem:

Grafana Version: Grafana v11.1.0-69950 (a4bb4c8400)
Zabbix Version: 6.4.0
Grafana-Zabbix-Version: 4.4.9

**Comment by zoltanbedi** [comment]
Sorry this is a problem in grafana. Please update your grafana. See https://github.com/grafana/grafana/pull/87211
