### ISSUE TITLE
Problems Issue with Zabbix 7.0 beta 2

### ISSUE THREAD

**Issue by christos-diamantis** [grafana/grafana-zabbix#1809]
When querying Problems, we get an Invalid parameter error.

![vmware_uKmFZqAmL8](https://github.com/grafana/grafana-zabbix/assets/154525755/852fb182-9de1-46e6-ba6a-1178b3e45c9a)

Log Line during the error:

logger=plugin.alexanderzobnin-zabbix-datasource t=2024-04-04T21:18:06.90846898+03:00 level=error msg="Zabbix API request error" error="Invalid params. Invalid parameter \"/output/2\": value must be one of \"proxyid\", \"name\", \"operating_mode\", \"description\", \"allowed_addresses\", \"address\", \"port\", \"tls_connect\", \"tls_accept\", \"tls_issuer\", \"tls_subject\", \"custom_timeouts\", \"timeout_zabbix_agent\", \"timeout_simple_check\", \"timeout_snmp_agent\", \"timeout_external_check\", \"timeout_db_monitor\", \"timeout_http_agent\", \"timeout_ssh_agent\", \"timeout_telnet_agent\", \"timeout_script\", \"lastaccess\", \"version\", \"compatibility\"."

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ---------| ------------- | ------------------- |
|  10.4.1   | 7.0.0 beta 2  |    4.4.6                 |

Will try to check the Zabbix documentation for API changes of Problems on Zabbix v.7.0.0

Also note, this issue is happening from alpha versions of Zabbix v.7.0.0

**Comment by christos-diamantis** [comment]
Changes of Zabbix API for problems in v.7.0.0:

https://www.zabbix.com/documentation/devel/en/manual/api/changes#problem

**Comment by zoltanbedi** [comment]
Hey @christos-diamantis thanks for opening this issue. We didn't add support for version 7 yet. We are tracking that in [this](https://github.com/grafana/grafana-zabbix/issues/1714) issue so I'm going to close this.

**Comment by ismaelfre10** [comment]
I have the same problem.

Grafana 9.3.6 
Grafana Plugin 4.5.2
Zabbix 7.03
