### ISSUE TITLE
An error occured within the plugin

### ISSUE THREAD

**Issue by NotTheRealAdam** [grafana/grafana-zabbix#1810]
**Describe the bug**

When trying to setup the plugin for Zabbix within Grafana, when saving it an error appears at the bottom stating 'An Error occured within the plugin'.

**Expected behavior**
The expected behavior is for this to save successfully and work correctly. 

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/136719435/4a303c36-170e-4fda-a1cb-2136e16802d4)

![image](https://github.com/grafana/grafana-zabbix/assets/136719435/f40aacb7-f514-4bbc-a4ef-9c02a6b3fda8)

**Network data**
N/A

**Software versions**

Grafana: 10.4.1 (OSS Version)
Grafana Plugin: 4.4.6

**Enviroment**
Server 1 OS: Windows Server 2019 Standard
Server 2 Zabbix: Appliance Version 5 

Plugin installed via the CLI **grafana-cli plugins install alexanderzobnin-zabbix-app**
Grafana installed on the E drive of Server 1
Both OS, Zabbix and Grafana are fresh installs however within the production enviroment, we have this issue with instances that have been running for a long time. 

(All within a my personal dev enviroment)

If anymore information is required, please let me know. Happy to assist where possible.

**Comment by NotTheRealAdam** [comment]
Any update here?

**Comment by gustavogurg** [comment]
Having the same issue. Did any of you guys manage to fix it somehow?

**Comment by XavierMace** [comment]
We've also started seeing this issue out of the blue.  

Grafana 10.3.3, 10.4.2
Plugin: 4.4.8
Grafana OS:  RHEL 8.9
Zabbix Servers:  6.4.10, 6.4.13, 7.0.0beta2

Plugin installed/updated  via the CLI.  We've got 3 separate Zabbix datasources running different Zabbix versions as noted above and they're all affected.

Only error in /var/log/grafana/grafana.log:

logger=context userId=22 orgId=1 uname="*redacted*" t=2024-04-24T13:13:13.937151263-07:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: [plugin.unavailable] plugin unavailable" remote_addr=***.**.**.*** traceID=

**Comment by NotTheRealAdam** [comment]
I have not been able to fix this, unfortunately. 
I may start looking at pulling a copy of this plugin and trying to dedicate some time looking at fixing this. 
If anyone else is interested hmu

**Comment by gustavogurg** [comment]
Im very insterested as the issue persists here. Please if you find any way around it let us know.

**Comment by XavierMace** [comment]
I found another post on here reporting the same error and a user provided this response:

i've found the solution, and the cause.
on my side it was because the system is hardened and the mount option on /var/lib was set to noexec.
if you got this error try to change the Plugin path of grafana, i set mine on /srv/ and it work perfectly

I can confirm that was my issue as well.  After moving the plugins to /opt/grafana in my case, all was well.

**Comment by NotTheRealAdam** [comment]
My instance is windows but ill take a look!

**Comment by NotTheRealAdam** [comment]
Well, I took a look and for my Windows Instance this doesnt help!

**Comment by NotTheRealAdam** [comment]
I am gonna drop all my troubleshooting here as I try to figure out the issue -
All a personal lab enviroment.

Logs - 
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:15:28.7769404+01:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: [plugin.unavailable] plugin unavailable" remote_addr=10.16.192.26 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:15:28.7769404+01:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=10.16.192.26 time_ms=25 duration=25.0811ms size=116 referer=http://10.16.192.26:3000/connections/datasources/edit/edhr4ihh140e8a handler=/api/datasources/:id/resources/* status_source=downstream
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:19.0722269+01:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: [plugin.unavailable] plugin unavailable" remote_addr=10.16.192.26 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:19.0722269+01:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=10.16.192.26 time_ms=2 duration=2.0007ms size=116 referer=http://10.16.192.26:3000/connections/datasources/edit/edhr4ihh140e8a handler=/api/datasources/:id/resources/* status_source=downstream
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:32.6890599+01:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: [plugin.unavailable] plugin unavailable" remote_addr=10.16.192.26 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:32.6900589+01:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=10.16.192.26 time_ms=1 duration=1.4446ms size=116 referer=http://10.16.192.26:3000/connections/datasources/edit/edhr4ihh140e8a handler=/api/datasources/:id/resources/* status_source=downstream
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:42.8111232+01:00 level=error msg="Internal server error" error="[plugin.downstreamError] client: failed to call resources: [plugin.unavailable] plugin unavailable" remote_addr=10.16.192.26 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-04-26T20:17:42.8111232+01:00 level=error msg="Request Completed" method=POST path=/api/datasources/1/resources/zabbix-api status=500 remote_addr=10.16.192.26 time_ms=1 duration=1.9982ms size=116 referer=http://10.16.192.26:3000/connections/datasources/edit/edhr4ihh140e8a/ handler=/api/datasources/:id/resources/* status_source=downstream
logger=plugins.update.checker t=2024-04-26T20:19:39.7576469+01:00 level=info msg="Update check succeeded" duration=5.4518341s
logger=cleanup t=2024-04-26T20:19:40.4677575+01:00 level=info msg="Completed cleanup jobs" duration=8.8311269s

**Comment by NotTheRealAdam** [comment]
Spent a good 1 hour on this and couldnt get it fixed 👎

**Comment by NotTheRealAdam** [comment]
Anyone have any luck with the Windows version of this?

**Comment by NotTheRealAdam** [comment]
I guess this one is going to die out?

**Comment by jadezi** [comment]
Have you tried adding the directory of the plugin to the system environment variable？

**Comment by NotTheRealAdam** [comment]
> Have you tried adding the directory of the plugin to the system environment variable？

I have but are you able to provide this for a windows installation in case I have done something wrong.

**Comment by jadezi** [comment]
I just tried and it has been successful.
You need to add the plugin directory to the system variable PATH

![image](https://github.com/grafana/grafana-zabbix/assets/46995667/ef56e4f2-907c-49b8-baf9-68aa421f152e)

**Comment by NotTheRealAdam** [comment]
Ah, I was looking within Grafana itself :|

**Comment by NotTheRealAdam** [comment]
Ill give this a try and come back to you.

**Comment by NotTheRealAdam** [comment]
I can confirm, tha got that work. 
Very odd that was the fix. 
@jadezi answer is correct. I shall close this with this comment now. 

Thank you to the community for assisting with this.

**Comment by mnzarthur** [comment]
can you help me?
https://github.com/grafana/grafana-zabbix/issues/1829

**Comment by mrcavisg** [comment]
I followed the procedure of adding the file path of the plugin folder to the SYSTEM VARIABLE (PATH) on my Windows machine where Grafana is running, and then restarted the services. However, it still didn't work. I have tried various procedures without success. I'm using the appliance on Hyper-V, and Grafana is running directly on Windows 10. The network communication between both works normally.
