### ISSUE TITLE
Grafana after acknowladge 

### ISSUE THREAD

**Issue by ekorre-it** [grafana/grafana-zabbix#1820]
Hello, I need a function. I have a dashboard with an issue with Zabbix. I want the issue to not be visible on the dashboard when I tick acknowledge

**Comment by LumePart** [comment]
Hey!
The plugin actually has this function already when querying problems (under the options tab) 
![image001 (2)](https://github.com/grafana/grafana-zabbix/assets/46826542/9162928c-510f-4b98-af74-af6b552f0530)

**Comment by zoltanbedi** [comment]
Thanks @LumePart for answering this.
