### ISSUE TITLE
Can't read Zabbix issues after Zabbix 7 upgrade

### ISSUE THREAD

**Issue by EHRETic** [grafana/grafana-zabbix#1833]
**Describe the bug**
I get an error message on Zabbix problem dashboard like this:

**Error**
`Invalid params. Invalid parameter "/output/2": value must be one of "proxyid", "name", "proxy_groupid", "local_address", "local_port", "operating_mode", "allowed_addresses", "address", "port", "description", "tls_connect", "tls_accept", "tls_issuer", "tls_subject", "custom_timeouts", "timeout_zabbix_agent", "timeout_simple_check", "timeout_snmp_agent", "timeout_external_check", "timeout_db_monitor", "timeout_http_agent", "timeout_ssh_agent", "timeout_telnet_agent", "timeout_script", "timeout_browser", "lastaccess", "version", "compatibility", "state".`

**Expected behavior**
That I can display the different open issues like with previsous version (same query works fine with 6.4.x)
(PS: it's an integration instance, no rush, but I wanted to give the feedback)

**Screenshots**

Error message:
![image](https://github.com/grafana/grafana-zabbix/assets/28634810/21ac2012-a840-4f8f-93dc-0f3235f4210b)

Dashboard:
![image](https://github.com/grafana/grafana-zabbix/assets/28634810/f98d5516-a2bc-4fb0-8847-0a97fe2e3390)

Query:
![image](https://github.com/grafana/grafana-zabbix/assets/28634810/d2ba27e7-a0fd-4357-a591-a373c9f38cc2)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| v10.4.3  | 7.0.0  | 4.4.9                 |

**Comment by the-iot** [comment]
we have the same issues after upgrade to Zabbix 7.0

**Comment by anthonysomerset** [comment]
already being tracked in #1714 1714

**Comment by EHRETic** [comment]
> already being tracked in #1714

Sorry, I didn't find it with search 😉

**Comment by EHRETic** [comment]
> already being tracked in #1714

Sorry, I didn't find it with search 😉
