### ISSUE TITLE
Query type "Problems" returns an error

### ISSUE THREAD

**Issue by trt19** [grafana/grafana-zabbix#1837]
**Describe the bug**
Query type "Problems" returns the following error:
'Query error
Invalid params. Invalid parameter "/output/2": value must be one of "proxyid", "host", "status", "description", "lastaccess", "tls_connect", "tls_accept", "tls_issuer", "tls_subject", "proxy_address", "auto_compress", "version", "compatibility".'

**Expected behavior**
The query should return a list of problems.

**Screenshots**
![image](https://github.com/grafana/grafana-zabbix/assets/35784020/05b8c030-3d3c-47cf-8a27-fdbe8a6677ff)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
|10.4.2 |6.4.14|4.5.0                 |

**Comment by ismolojy** [comment]
+1
<html>
<body>

Grafana | Zabbix | Grafana-Zabbix Plugin
-- | -- | --
11.0.0 | 6.4.6 | 4.5.0


</body>
</html>

**Comment by rike50** [comment]
Same issue. Only upgrade from 4.4.9.


Grafana | Zabbix | Grafana-Zabbix Plugin
11.0.0 | 6.4.14 | 4.5.0

**Comment by rafaelbagattini** [comment]
+1

Grafana v11.0.0 (Docker)
Zabbix 7.0.0 (Docker)
Plugin 4.5.0

**Comment by willianhess** [comment]
Same issue, new instalation.

Grafana | Zabbix | Grafana-Zabbix Plugin
  11.0.0  | 6.4.14  | 4.5.0

**Comment by zoltanbedi** [comment]
Sorry, this is fixed in 4.5.1
