### ISSUE TITLE
Failed to install plugin

### ISSUE THREAD

**Issue by BiggieN** [grafana/grafana-zabbix#1850]
**Describe the bug**
Good day. I have a problem installing a plugin in the grafana web interface. Grafana is installed locally on kde neon, the plugin was installed by the command grafana-cli plugins install alexanderzobnin-zabbix-app. In the web interface, I went to Administration - Plugins and data - Plugins, chose Zabbix plugin, then clicked install and got the following error. All this was done via VPN. Can you tell me where I can view the installation logs?

**Expected behavior**
Plugin installed successfully

**Screenshots**
![Screenshot_20240706_220553](https://github.com/grafana/grafana-zabbix/assets/2116114/9389e954-7233-4567-8594-fc2485819020)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 11.1.0   | x.x.x  | 4.5.2                 |

**Comment by BiggieN** [comment]
Logs show this: logger=context userId=1 orgId=1 uname=admin t=2024-07-07T11:56:07.402106392+03:00 level=error msg="Failed to install plugin" error="failed to extract plugin archive: unlinkat /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/styles/light.css: permission denied" remote_addr=127.0.0.1 traceID=
logger=context userId=1 orgId=1 uname=admin t=2024-07-07T11:56:07.402400285+03:00 level=error msg="Request Completed" method=POST path=/api/plugins/alexanderzobnin-zabbix-app/install status=500 remote_addr=127.0.0.1 time_ms=560 duration=560.51825ms size=51 referer=http://127.0.0.1:3000/plugins/alexanderzobnin-zabbix-app handler=/api/plugins/:pluginId/install status_source=server

I tried to add full permissions for all for /var/lib/grafana and subfolders, but it didn't helped.

**Comment by marcelordeo** [comment]
Dear,

I have this problem too.
I haven't found a solution yet.

It started in version 4.5.2

**Comment by eneidercolina** [comment]
Here is the solution

[https://github.com/grafana/grafana-zabbix/issues/1631#issuecomment-2200035463](url)

**Comment by marcelordeo** [comment]
Hello, thanks for the feedback.

The link is not available or is broken. :(

**Comment by marcelordeo** [comment]
Hello,

It worked like this for me,

chown -R grafana.grafana /var/lib/grafana/plugins/
systemctl restart grafana-server

grafana-cli plugins  uninstall alexanderzobnin-zabbix-app
rm -rf /var/lib/grafana/plugins

And I installed the plugin via WEB.

It worked perfectly.

**Comment by Leonamsm2** [comment]
> Hello,
> 
> It worked like this for me,
> 
> chown -R grafana.grafana /var/lib/grafana/plugins/ systemctl restart grafana-server
> 
> grafana-cli plugins uninstall alexanderzobnin-zabbix-app rm -rf /var/lib/grafana/plugins
> 
> And I installed the plugin via WEB.
> 
> It worked perfectly.

solved my problem, thanks!

**Comment by vinhhq1** [comment]
> Logs show this: logger=context userId=1 orgId=1 uname=admin t=2024-07-07T11:56:07.402106392+03:00 level=error msg="Failed to install plugin" error="failed to extract plugin archive: unlinkat /var/lib/grafana/plugins/alexanderzobnin-zabbix-app/styles/light.css: permission denied" remote_addr=127.0.0.1 traceID= logger=context userId=1 orgId=1 uname=admin t=2024-07-07T11:56:07.402400285+03:00 level=error msg="Request Completed" method=POST path=/api/plugins/alexanderzobnin-zabbix-app/install status=500 remote_addr=127.0.0.1 time_ms=560 duration=560.51825ms size=51 referer=http://127.0.0.1:3000/plugins/alexanderzobnin-zabbix-app handler=/api/plugins/:pluginId/install status_source=server
> 
> I tried to add full permissions for all for /var/lib/grafana and subfolders, but it didn't helped.

where can i find the log bro?

**Comment by zoltanbedi** [comment]
I'm going to close this issue as it was already figured out and was not an issue with the plugin. The correct link above is https://github.com/grafana/grafana-zabbix/issues/1631#issuecomment-2200035463
