### ISSUE TITLE
"Angular plugins are not supported"

### ISSUE THREAD

**Issue by cdlili** [grafana/grafana-zabbix#1862]
**Describe the bug**
I upgraded to Grafana version v11.1.3 from v9.6.4 (if i remember correctly). The Zabbix plugin is no longer working and when i try to view the data source it says "Angular plugins are not supported".

**Expected behavior**
I have read https://grafana.com/docs/grafana/latest/developers/angular_deprecation/ and made sure that "angular_support_enabled = true" is in the grafana.ini under /etc/grafana.

Is there no support for the plugin on the running versions? Any suggestions?

**Screenshots**
See attached.

**Network data**
-

**Software versions**
Zabbix 6.2.9
Grafana v11.1.3
![Zabbix](https://github.com/user-attachments/assets/3a403f97-2edb-4119-b249-fbae2c3b94d6)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| x.x.x   | x.x.x  | x.x.x                 |

**Comment by ivanahuckova** [comment]
> I got it working, didn't realize that the line was ";" (commented out). Everything's working now.

Thank you for confirming!
