### ISSUE TITLE
Tests fails with go 1.23 due to panic in pyroscope-go/godeltaprof v0.1.7

### ISSUE THREAD

**Issue by Antiz96** [grafana/grafana-zabbix#1874]
**Describe the bug**
Building grafana-zabbix with go 1.23 and running tests fails with

```
panic: pattern "GET /debug/pprof/" (registered at /usr/local/go/src/net/http/pprof/pprof.go:100) conflicts with pattern "/debug/pprof/delta_heap" (registered at /go/pkg/mod/github.com/grafana/pyroscope-go/godeltaprof@v0.1.7/http/pprof/pprof.go:24):

	GET /debug/pprof/ matches fewer methods than /debug/pprof/delta_heap, but has a more general path pattern
```

This is due to a panic on go 1.23 in pyroscope-go/godeltaprof
Related upstream issue: https://github.com/grafana/pyroscope-go/issues/118

**Expected behavior**
Tests pass without panic

**Screenshots**
NA

**Network data**
NA

**Software versions**

NA

I opened a PR to fix this at https://github.com/grafana/grafana-zabbix/pull/1875

**Comment by ivanahuckova** [comment]
fixed by https://github.com/grafana/grafana-zabbix/pull/1877
