### ISSUE TITLE
(Question) Move the action column to another location.

### ISSUE THREAD

**Issue by bankir82** [grafana/grafana-zabbix#1892]
Hello
Is there any way to move this column with actions from the rightmost position to another place (I would like to take the first place)? Because on the phone you need to scroll to the right and press this button, and then scroll back to the left to close the problem
![Image](https://github.com/user-attachments/assets/a105899f-2201-45f0-bceb-c732194aa847)
Latest version zabbix and grafana

**Comment by zoltanbedi** [comment]
it is not possible. Propose a feature request for it and you can even raise a PR. I can help you get that merged.
