### ISSUE TITLE
Display groups only, which has active alarms

### ISSUE THREAD

**Issue by mmip-labs** [grafana/grafana-zabbix#1895]
Hi there!

Grafana 11.2.2, Zabbix 6.0, Plugin 4.5.5

How can display in table only groups, which have at least one  active trigger and hide, if group does not have any active triggers?

![Image](https://github.com/user-attachments/assets/95f39a71-2703-4d03-a440-c85a517c2160)![Image](https://github.com/user-attachments/assets/821c3524-c33f-4b83-a1f2-65ec80b97851)

In version 4.2.10, for example, it was working by default

**Comment by mmip-labs** [comment]
I resolve this issue by adding filter:

![Image](https://github.com/user-attachments/assets/1223b16e-b974-460a-92de-33613be7094b)

**Comment by zoltanbedi** [comment]
I'm happy you were able to resolve your issue.
