### ISSUE TITLE
Zabbix Datasource not displayed

### ISSUE THREAD

**Issue by Dark-ZBX** [grafana/grafana-zabbix#1905]
Hi!

I can't add zabbix datacource because it is not displayed in the plugins section

I added the allow_loading_unsigned_plugins line and restarted grafana but it didn't work

![Image](https://github.com/user-attachments/assets/d445bdb9-0f6d-41ad-b141-e42934960749)

any suggestion?

**Software versions**

Zabbix plugin 4.5.6

Zabbix 6.4.14

Grafana v11.2.2

regards!

**Comment by Mickael-Martin** [comment]
Hello, Please check plugin is enabled in plugins view!

**Comment by opus91** [comment]
You're displaying only installed plugins ,make sure to choose all 

![Image](https://github.com/user-attachments/assets/7cc77add-0338-4fb2-b3ff-35208aef7416)

**Comment by zoltanbedi** [comment]
This is not an error in the plugin probably bad install.
