### ISSUE TITLE
Grafana 6.2 not supported?

### ISSUE THREAD

**Issue by Julzorensen** [grafana/grafana-zabbix#737]
Grafana-Zabbix failed to connect to the Zabbix DB under Grafana **6.2**-beta1.

An error message states that the "connection to the Zabbix DB failed".
When you go to the Zabbix plugin configuration page, ### nothing shows up.

It's kind of sad since Grafana 6.2 fixes the native connector to ElasticSearch version7, but breaks the Zabbix plugin.

Anyone else facing this?
Is anything already planned?

**Comment by alaled** [comment]
Probably same as #738?

**Comment by Julzorensen** [comment]
More than probably the same, indeed.

We posted this almost at the same time.
