### ISSUE TITLE
Incompatibility between zabbix-app 3.10.2 and grafana-6.2.0

### ISSUE THREAD

**Issue by DarkZatarra** [grafana/grafana-zabbix#738]
There is an incompatibility between:

alexanderzobnin-zabbix-app @ 3.10.2

and 

grafana-6.2.0-beta1.x86_64

This is the error message:

Zabbix plugin failed
Error: Fetch error: 404 Not Found Instantiating http://x.x.x.x:3000/public/app/core/utils/datemath Loading http://x.x.x.x:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module

It seems that this file is missing: /usr/share/grafana/public/app/core/utils/datemath.ts

I've checked the packages files and it seems that only version grafana-6.0.0-beta3.x86_64 has that file:

grafana-6.0.0-beta3.x86_64 : Grafana
Repo        : grafana
Matched from:
Filename    : /usr/share/grafana/public/app/core/utils/datemath.ts

I managed to use zabbix plugin by downgrading from 6.2.0-beta1 to 6.0.0-beta3

**Comment by volter** [comment]
Is this ticket still relevant? 6.3 is current and I'm using it with version 3.10.4 of the plug-in without any issues.
