### ISSUE TITLE
With release of Zabbix 4.0.8 singlestat Triggers query mode stopped working

### ISSUE THREAD

**Issue by 7abbix** [grafana/grafana-zabbix#745]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Network data**
If it's related to metric data visualization would be great to get the raw query and response for the network request (check this in browser dev tools network tab, there you can see metric requests, please include the request body and request response)

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| 6.1.3 | 4.0.8 | 3.10.2|

**Comment by 7abbix** [comment]
Zabbix server rollback did not help.
Restored snapshots on all machines: Zabbix server, database and grafana.

**Comment by gabrielleiteecore** [comment]
Hey man!

I'm facing this same issue. Have you found any solution?

**Comment by 7abbix** [comment]
Hi, I updated to latest zabbix, latest grafana and latest grafana-zabbix plugin and singlestats got back working
