### ISSUE TITLE
Feature Request: Allow additional query types for variables

### ISSUE THREAD

**Issue by dmajere** [grafana/grafana-zabbix#761]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to have an ability to query host list with hosts that have specific application

**Describe the solution you'd like**
Allow {$group}{*}{$application} query for variables.
This query type should pass applicationids to hosts.get method 

**Describe alternatives you've considered**
None, passing applicationids is the easiest to implement

**Comment by matiasba** [comment]
It would be very useful to also be able to find groups that interject multiple groups. For example, I have a group for all hosts on a site which it may have switches, those switches are also in the switches group. Well with something like this I would be able to show only the sites that have switches in them. I guess that this also would be possible if we could filter groups which contain host that match a regex.
