### ISSUE TITLE
Data has disappeared

### ISSUE THREAD

**Issue by sboyd67** [grafana/grafana-zabbix#771]
Good morning! 
We have Grafana 5.1.3 with the Zabbix plugin 3.10.2.  Everything was running great but now we can't see any data prior to July 16.  We're not sure what happened.  But we're hoping we can figure out how to get to the data prior to this time.  The data is in Zabbix but it doesn't show in Grafana (see screenshot).
![image](https://user-images.githubusercontent.com/3776462/61736298-c3c6fe80-ad53-11e9-8d1b-a7e7177e51ab.png)

**Comment by sboyd67** [comment]
As a side note, the data does show up in Zabbix prior to that date.  Any help is appreciated.

**Comment by silveraignacio** [comment]
Hi! Probably you have to enable "Trends" checkbox on datasource configuration. It seems to be the root cause of your issue regarding the dates that grafana is displaying data (7 days - normal history time on zabbix)
Please enable trends an let us know if it fix your issue

Regards

**Comment by sboyd67** [comment]
Thank you so much for your help!!!  This has been bugging me for a few weeks.  That fixed the issue.
Best regards,
Steve

    On Friday, July 26, 2019, 8:04:50 AM EDT, silveraignacio <notifications@github.com> wrote:  
 
 
Hi! Probably you have to enable "Trends" checkbox on datasource configuration. It seems to be the root cause of your issue regarding the dates that grafana is displaying data (7 days - normal history time on zabbix)
Please enable trends an let us know if it fix your issue

Regards
