### ISSUE TITLE
Plugin not stable in constant run

### ISSUE THREAD

**Issue by Yotouille** [grafana/grafana-zabbix#898]
Hi there,

We are trying to build a wall screen constantly displaying dashboard, but it is not that easy... I have seen a dashboard going ok for a couple of days but that was a record, sometimes it only needs a few hours to break.

Here are the issue we ran into:
    - RAM: is filled until OS become unresponsive (Win10)
    - Firefox: graphs freeze (loading wheel turning forever)
    - Chrome: tab just crash on itself
    - Firefox+Chrome: sometimes graphs will just become empty with "query error: 504 gateway timeout"

Same behavior with dongle like ChromeCast or AirTame (originally this was why we powered-on a real computer, for testing purpose)

Each time the issue comes up, when the whole machine do not become unstable/dead, the only living thing on the dashboard is a graph from an ElasticSearch data source, this comfort us in the fact that this issue do not come from Grafana but is isolated on our Zabbix graphs.

We have done any necessary (and beyond) mods on timeouts and buffer size, webserver-side and php-side

Zabbix: 4.0
Plugin: 3.10.5
Grafana: 6.5.1 (1763a0f)

BTW, thanks for all this work. Bye !

**Comment by alexanderzobnin** [comment]
Hi! Do you see any errors on the Zabbix side (php, database, etc)?
