### ISSUE TITLE
Zabbix datasource Server mode still uses browser connection

### ISSUE THREAD

**Issue by bagelben** [grafana/grafana-zabbix#910]
**Describe the bug**
When setting up the Zabbix datasource, I have set the access settings as Server (I guess this was formerly known as proxy). However when connecting to my Zabbix server it required that I have access in my browser, which seems like it is still using browser mode. 

We have connectivity between Grafana server and our Zabbix server, but not necessarily between the client accessing Grafana and the Zabbix Server. In this case the Zabbix plugin is unable to load any items unless we set up a tunnel and change the datasource address to use this. 

**Expected behavior**
Zabbix datasource in Server mode should be able to route requests via the Grafana Server

**Screenshots**
If required I can dig some out, but I do not have them available on this laptop.

**Software versions**

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| ------- | ------ | --------------------- |
| 6.5.1   | 3.4.9  | 3.10.4                 |

**Comment by alexanderzobnin** [comment]
Could you provide errors you get? Grafana logs and screenshots would be helpful. Also, keep in mind that Zabbix exposes its API through Zabbix frontend. So grafana server should have access to the Zabbix frontend server (where PHP is running) and not the Zabbix server itself.
