### ISSUE TITLE
Grafana 7 connect to  Zabbix 5 on Raspberry pi 4B : Could not connect to given url

### ISSUE THREAD

**Issue by stephanepapin** [grafana/grafana-zabbix#951]
**Trying to connect Grafana to Zabbix on RapsberryPi 4B-4Gb (Arm7), Raspbian full, but get '_Could not connect to given url_' in Grafana Data Sources GUI**

My RPI have zabbix server/agent/grafana installed.
Zabbix GUI  : 192.168.1.16:81/zabbix (I've used port 81, because 80 used by OpenMediaVault
Grafana GUI : 192.168.1.16:3000 

Zabbix server and agent working fine.

I've created an dedicated user for Zabbix API with password simple, without ' and " to avoid issue in curl.

I've tried in command line : 
 sudo curl  -H "Content-Type: application/json-rpc" -X POST  http://192.168.1.15:81/api_jsonrpc.php -d '{"jsonrpc":"2.0","method":"user.login","id":1,"auth":null,"params":{"user": "zbx_api","password": "_mypassword_"}}'
Returned :
{"jsonrpc":"2.0","result":"7cd4c83aa46f5753d270609b8dcd6610","id":1}
![pi_zbx_grafana](https://user-images.githubusercontent.com/65684371/82497358-67a54600-9aee-11ea-93f4-6d39da2580e5.png)

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------- | -------- | --------------------- |
|   v7.1.1 (3039f9c3bd)   |   5.0.1    |  3.12.3         |

**Comment by alexanderzobnin** [comment]
You said you have Zabbix on `192.168.1.16`, but entered `192.168.1.15`. Doesn't it a reason?

**Comment by ismaelmano7** [comment]
I am also having the same problem, I have been trying to configure for two days, but without success.
![image](https://user-images.githubusercontent.com/43354334/82587806-340b0000-9b70-11ea-8598-143053abba51.png)

**Comment by ismaelmano7** [comment]
Just to reinforce, the plugin worked normally, with zabbix in version 3.4 and Grafana in version 6 ... After updating zabbix to version 5.0 and grafana to version 7.0, it stopped working.

**Comment by stephanepapin** [comment]
> You said you have Zabbix on `192.168.1.16`, but entered `192.168.1.15`. Doesn't it a reason?

Hi Mistake from me : 192.168.1.15 in all case :)

**Comment by fushengbao** [comment]
God, I also encountered this problem, who can tell me what to do

**Comment by cendudu** [comment]
good afternoon!

I'm also having the same problem, it doesn't make the connection.

**Comment by fushengbao** [comment]
> God, I also encountered this problem, who can tell me what to do

No problem with zabbix4.0

**Comment by chladic** [comment]
In prerequisites is grafana 6.x so probably not yet supported ?

**Comment by silveraignacio** [comment]
I think it can sounds stupid but have you selected the correct zabbix version in combo box on data source config
In the first image it is configured with version 4.X, if you have version 5.0 it must cause the issue

**Comment by stephanepapin** [comment]
> I think it can sounds stupid but have you selected the correct zabbix version in combo box on data source config?
> In the first image it is configured with version 4.X, if you have version 5.0 it must cause the issue

Just see this version item, but I've retried, no way to find in datasource config panel

**Comment by silveraignacio** [comment]
Weird! It is present on version 3.10.2 but I hadn't got time to test the new one. I had this issue before. Plugin was not able to connect to zabbix due to combo box version.

**Comment by stephanepapin** [comment]
I've just test direct connect to zabbix mysql DB working

**Comment by KostyaEsmukov** [comment]
After upgrading Zabbix to 5.0 and Grafana to 7.0 I have got the "Could not connect to given url" error.

For me the cause was that the official Zabbix web docker container has changed HTTP port from 80 to 8080: https://github.com/zabbix/zabbix-docker/issues/602

So changing the url from `http://zabbix_web/api_jsonrpc.php` to `http://zabbix_web:8080/api_jsonrpc.php` has fixed the issue for me.

The Plugin version is 3.12.0, I didn't notice any other issues.

**Comment by stephanepapin** [comment]
> After upgrading Zabbix to 5.0 and Grafana to 7.0 I have got the "Could not connect to given url" error.
> 
> For me the cause was that the official Zabbix web docker container has changed HTTP port from 80 to 8080: [zabbix/zabbix-docker#602](https://github.com/zabbix/zabbix-docker/issues/602)
> 
> So changing the url from `http://zabbix_web/api_jsonrpc.php` to `http://zabbix_web:8080/api_jsonrpc.php` has fixed the issue for me.
> 
> The Plugin version is 3.12.0, I didn't notice any other issues.

I'm using dedicated port for my front

**Comment by stephanepapin** [comment]
> I've just test direct connect to zabbix mysql DB working

connection to DB is ok but still issue with

**Comment by stephanepapin** [comment]
Update version of all components to :

| Grafana | Zabbix | Grafana-Zabbix Plugin |
| -------- | -------- | --------------------- |
|   v7.1.1 (3039f9c3bd)   |   5.0.1    |  3.12.3         |

Still same issue

**Comment by jividijuvent** [comment]
> After upgrading Zabbix to 5.0 and Grafana to 7.0 I have got the "Could not connect to given url" error.
> 
> For me the cause was that the official Zabbix web docker container has changed HTTP port from 80 to 8080: [zabbix/zabbix-docker#602](https://github.com/zabbix/zabbix-docker/issues/602)
> 
> So changing the url from `http://zabbix_web/api_jsonrpc.php` to `http://zabbix_web:8080/api_jsonrpc.php` has fixed the issue for me.
> 
> The Plugin version is 3.12.0, I didn't notice any other issues.

This worked for me, Seems that URL for Zabbix API has been changed in version 5, I replaced "zabbix/api_jsonrpc.php" with just "api_jsonrpc.php" and connected successfully.

**Comment by stephanepapin** [comment]
Fine working 
http://myzabbixserverip:myfrontport/api_jsonrpc.php
